SELECT FUNCOD, FUNDES, FunSit
FROM DB_RHCB.SchRH.FUN
WHERE FUNSIT = 'A'
AND FUNDES LIKE '%DADOS%';

SELECT FUCCVLCPF, FUCCVLNOM, FUCCVLSEX, FUCCVLADIDAT, OPMCOD, FUCCVLCPFDGT, CPF, FUCCVLNASDAT, FUCCVLTIP, PrsEmpCod, FunCvlSaiDat, LeiIdf
FROM DB_RHCB.SchRH.FUCCVL
WHERE FUCCVLCPF = 439193068;




----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--QRU DO TEN CIPRIANO

SELECT * FROM [DB_RHCB].[SchRH].[PM] 
WHERE PMRENUM= 193375

SELECT OPMCOD, OPMN01DES, OPMN02DES, OPMN03DES, OPMN04DES, OPMN05DES, OPMN06DES, OPMSIT, MUNCOD, OPMEND, OPMCPL, OPMBAI, CEPNUM, OPMTIP, OPMEMA, OPMANTCOD, SRVCOD, OPMVFRCOD, OPMCHFCOD, ZNAMUNCOD, OPMCABATU, OPMOPRIDF, OPMCABORI, OPMUTMX, OPMUTMY, OPMPBCBLTNUM, OPMEFEFIX, OPMDEFTSOIND, OPMDEFTPOIND, OPMQTDRAIKM, COPMORG, OPMORG1, OPMORG2, OpmApe, OpmHrq, OpmGeog, OpmEscCraFlg, OpmIclDat, OpmIclNumCpf, OpmAltDat, OpmAltNumCpf
FROM DB_MUNICIPIO_OPM.dbo.OPM
WHERE OPMCOD in(700004130, 700004180);

SELECT 
	POS_GRAD, RE, DIG, NOME, NOME_GUERRA, SITUACAO--, SEXO, QDRCOD, QDR, OPMCOD_EFETIVA, OPM_NOME_EFETIVA, OPMCOD_ATUAL, OPM_NOME_ATUAL, OPMCOD_ANTERIOR, OPM_NOME_ANTERIOR, GRD_CMD, BTL, CIA, UORCOD, UOR, DATA_INGRESSO, DATA_POSSE, EST_CVL, ESCOLARIDADE, RELIGIAO, DATA_NASC, CNH, VAL_CNH, CAT_CNH, CELULAR, TEL_FUNCIONAL, EMAIL_FUNCIONAL, EMAIL_PARTICULAR, CODBCO, BANCO, AGENCIA, CONTA, DGT_CONT, ALTURA, TIP_SANG, FTR_SANG, CUTIS, TIP_CBL, COR_CBL, NIVEL, ALMAN, DATA_ULT_PROM
	--EfetivoIdf, CPF, POSCOD, POS_GRAD, RE, DIG, NOME, NOME_GUERRA, SLGCOD, SITUACAO, SEXO, QDRCOD, QDR, OPMCOD_EFETIVA, OPM_NOME_EFETIVA, OPMCOD_ATUAL, OPM_NOME_ATUAL, OPMCOD_ANTERIOR, OPM_NOME_ANTERIOR, GRD_CMD, BTL, CIA, UORCOD, UOR, DATA_INGRESSO, DATA_POSSE, EST_CVL, ESCOLARIDADE, RELIGIAO, DATA_NASC, CNH, VAL_CNH, CAT_CNH, CELULAR, TEL_FUNCIONAL, EMAIL_FUNCIONAL, EMAIL_PARTICULAR, CODBCO, BANCO, AGENCIA, CONTA, DGT_CONT, ALTURA, TIP_SANG, FTR_SANG, CUTIS, TIP_CBL, COR_CBL, NIVEL, ALMAN, DATA_ULT_PROM
FROM DB_EFETIVO.SchEfetivo.Efetivo
WHERE OPMCOD_ATUAL = 700004180;

