

SELECT
	*
	--PesIdf, PesNom, PesSclNom, PesTipCod, PesNasDat, PesCpfMigNum, PesIclDat
FROM DB_CORP_CCB.SchCRPCCB.PES AS PES
INNER JOIN DB_CORP_CCB.SchCRPCCB.PESATVPRF AS PESATVPRF ON PESATVPRF.PesIdf = PES.PesIdf 
WHERE PesCpfMigNum = 32321548835;

SELECT AtvPrfCod, AtvPrfNom
FROM DB_CORP_CCB.SchCRPCCB.ATVPRF;

SELECT AtvPrfCod, PesIdf, PesAtvPrfIclDat
FROM DB_CORP_CCB.SchCRPCCB.PESATVPRF
WHERE PesIdf = 153927;

/* REGRAS DO MA */

SELECT SftCod, SftTipCod, SftClsCod, OpmCbIdf, SftNom, SftDes, SftAtvIdc, SftSgl, SftCpfIclNum, SftIclDat, CnmAreCod
FROM DB_CONAPLIC.SchCTRAPL.SFT
WHERE SftNom = 'MA'; --SftCod = 8

SELECT MnuSftCod, SftCod, SftTipCod, SftClsCod, MnuSftNom, MnuSftEnd, MnuSftAtvIdc
FROM DB_CONAPLIC.SchCTRAPL.MNUSFT
WHERE SftCod = 8; -- MnuSftCod = 8

SELECT GrpAcsCod, MnuSftFndCod, MnuSftCod, GrpAcsFndAtvIdc
FROM DB_MA.SchMA.GRPACSFND
WHERE MnuSftCod = 8; --GrpAcsCod = 22

SELECT GrpAcsCod, GrpAcsNom, GrpAcsAtvIdc, GrpAcsSlgNom
FROM DB_MA.SchMA.GRPACS
WHERE GrpAcsCod = 91--22;

SELECT GrpAcsRgaCod, GrpAcsCod, GrpAcsRgaNom, GrpAcsRgaAtvIdc
FROM DB_MA.SchMA.GRPACSRGA
WHERE GrpAcsCod = 91--22;

SELECT GrpAcsRgaCod, AtvPrfCod, GrpAcsRgaAtvPrfAtvIdc
FROM DB_MA.SchMA.GRPACSRGAATVPRF
WHERE AtvPrfCod = 2;


/* ======================================= REGRAS DE USUÁRIOS POR GRUPOS ======================================= */

--GERAL:
SELECT
	--*
	GRPACSRGA.GrpAcsRgaNom, VW_UOR.uor, VW_UOR.UorNome, VW_UOR.uoropm
	, RHCB.pos_grad, RHCB.re, RHCB.dgt, RHCB.nome, RHCB.situacao, RHCB.nome_guerra, RHCB.cpf, pes.pesidf
FROM DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK)
LEFT JOIN DB_MA.SchMA.GRPACSRGAUOR AS GRPACSRGAUOR WITH(NOLOCK) ON GRPACSRGAUOR.GrpAcsRgaCod = GRPACSRGA.GrpAcsRgaCod
LEFT JOIN [DB_MUNICIPIO_OPM].[SchUOR].[VW_UOR_OPM_UOROPM_UORHRQ] AS VW_UOR WITH(NOLOCK) ON GRPACSRGAUOR.UorCod = VW_UOR.uor
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON RHCB.OPM_ATUAL = VW_UOR.UorOpm AND RHCB.SLGCOD IN (1,2,3)
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ))
LEFT JOIN DB_MA.SchMA.GRPACSRGAATVTIP AS GRPACSRGAATVTIP WITH(NOLOCK) ON GRPACSRGAATVTIP.GrpAcsRgaCod = GRPACSRGA.GrpAcsRgaCod
--LEFT JOIN DB_MA.SchMA.GRPACSRGAATVPRF AS GRPACSRGAATVPRF WITH(NOLOCK) ON GRPACSRGAATVPRF.GrpAcsRgaCod = GRPACSRGA.GrpAcsRgaCod
--LEFT JOIN DB_CORP_CCB.SchCRPCCB.PESATVPRF AS PESATVPRF ON PESATVPRF.AtvPrfCod = GRPACSRGAATVPRF.AtvPrfCod AND PES.PesIdf = PESATVPRF.PesIdf
LEFT JOIN DB_MA.SchMA.GRPACSRGAPOS AS GRPACSRGAPOS WITH(NOLOCK) ON GRPACSRGAPOS.GrpAcsRgaCod = GRPACSRGA.GrpAcsRgaCod AND RHCB.POS_GRAD = GRPACSRGAPOS.POSCOD
LEFT JOIN DB_MA.SchMA.GRPACSRGAFUN AS GRPACSRGAFUN WITH(NOLOCK) ON GRPACSRGAFUN.GrpAcsRgaCod = GRPACSRGA.GrpAcsRgaCod
LEFT JOIN DB_MA.SchMA.GRPACSRGASRVTIP AS GRPACSRGASRVTIP WITH(NOLOCK) ON GRPACSRGASRVTIP.GrpAcsRgaCod = GRPACSRGA.GrpAcsRgaCod
WHERE GRPACSRGA.GrpAcsCod = 22
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1
	AND PES.PesIdf IS NOT NULL
	AND VW_UOR.UOR IS NOT NULL

-- UOR:
SELECT
	PES.Pesidf, GRPACS.GrpAcsCod, GRPACSRGA.GrpAcsRgaNom, GRPACSRGA.GrpAcsRgaAtvIdc, GRPACSRGAUOR.UorCod, GRPACSRGAUOR.GrpAcsRgaUorAtvIdc, PES.PesCpfMigNum, RHCB.POSCOD, RHCB.POS_GRAD, PES.PesNom
FROM DB_MA.SchMA.GRPACSRGAUOR AS GRPACSRGAUOR WITH(NOLOCK)
INNER JOIN DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK) ON GRPACSRGA.GrpAcsRgaCod = GRPACSRGAUOR.GrpAcsRgaCod
INNER JOIN DB_MA.SchMA.GRPACS AS GRPACS WITH(NOLOCK) ON GRPACS.GrpAcsCod = GRPACSRGA.GrpAcsCod
INNER JOIN [DB_MUNICIPIO_OPM].[SchUOR].[VW_UOR_OPM_UOROPM_UORHRQ] AS VW_UOR WITH(NOLOCK) ON GRPACSRGAUOR.UorCod = VW_UOR.uor
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON RHCB.OPM_ATUAL = VW_UOR.UorOpm AND RHCB.SLGCOD IN (1,2, 3)
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ))
WHERE GRPACSRGA.GrpAcsRgaCod = 22 
	AND GRPACSRGAUOR.GrpAcsRgaUorAtvIdc = 1 -- Regra Uor ativa
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1 -- Regra de acesso ativa
	AND VW_UOR.UorOpmAtvIdc = 1 -- Uor Ativa
	AND PES.PesIdf IS NOT NULL -- Quem não está na tabela PES não aparecerá (Inativos muito antigos)
	ORDER BY PES.PesNom
;

-- ATIVIDADE OPM:
SELECT
	PES.Pesidf, GRPACS.GrpAcsCod, GRPACSRGA.GrpAcsRgaNom, GRPACSRGA.GrpAcsRgaAtvIdc, UORSRVATV.UorCod, PES.PesCpfMigNum, RHCB.POSCOD, RHCB.POS_GRAD, PES.PesNom
FROM DB_MA.SchMA.GRPACSRGAATVTIP AS GRPACSRGAATVTIP
INNER JOIN DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK) ON GRPACSRGA.GrpAcsRgaCod = GRPACSRGAATVTIP.GrpAcsRgaCod
INNER JOIN DB_MA.SchMA.GRPACS AS GRPACS WITH(NOLOCK) ON GRPACS.GrpAcsCod = GRPACSRGA.GrpAcsCod
INNER JOIN DB_MUNICIPIO_OPM.SchUOR.UORSRVATV AS UORSRVATV ON GRPACSRGAATVTIP.AtvTipCod = UORSRVATV.AtvTipCod
INNER JOIN [DB_MUNICIPIO_OPM].[SchUOR].[VW_UOR_OPM_UOROPM_UORHRQ] AS VW_UOR ON VW_UOR.UOR = UORSRVATV.UorCod
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON RHCB.OPM_ATUAL = VW_UOR.UorOpm AND RHCB.SLGCOD IN (1,2,3)
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ))
WHERE GRPACSRGA.GrpAcsRgaCod = 22
	AND GRPACSRGAATVTIP.GrpAcsRgaAtvTipAtvIdc = 1 -- Regra Uor ativa
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1 -- Regra de acesso ativa
	AND VW_UOR.UorOpmAtvIdc = 1 -- Uor Ativa
;

-- ATIVIDADE PESSOA: (DEVERÁ SER FEITO SEPARADAMENTE)
SELECT 
	PES.Pesidf, GRPACS.GrpAcsCod, GRPACSRGA.GrpAcsRgaNom, GRPACSRGA.GrpAcsRgaAtvIdc, VW_UOR.Uor AS UorCod, PES.PesCpfMigNum, RHCB.POSCOD, RHCB.POS_GRAD, PES.PesNom
FROM DB_MA.SchMA.GRPACSRGAATVPRF AS GRPACSRGAATVPRF
INNER JOIN DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK) ON GRPACSRGA.GrpAcsRgaCod = GRPACSRGAATVPRF.GrpAcsRgaCod
INNER JOIN DB_MA.SchMA.GRPACS AS GRPACS WITH(NOLOCK) ON GRPACS.GrpAcsCod = GRPACSRGA.GrpAcsCod
INNER JOIN DB_CORP_CCB.SchCRPCCB.ATVPRF AS ATVPRF ON ATVPRF.AtvPrfCod =  GRPACSRGAATVPRF.AtvPrfCod
INNER JOIN DB_CORP_CCB.SchCRPCCB.PESATVPRF AS PESATVPRF ON PESATVPRF.AtvPrfCod = GRPACSRGAATVPRF.AtvPrfCod
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesIdf = PESATVPRF.PesIdf
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ) AND RHCB.SLGCOD IN (1,2, 3))
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ VW_UOR ON RHCB.OPM_ATUAL = VW_UOR.UorOpm
WHERE GRPACSRGA.GrpAcsRgaCod = 91
	AND GRPACSRGAATVPRF.GrpAcsRgaAtvPrfAtvIdc = 1 -- Regra Uor ativa
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1 -- Regra de acesso ativa
;

SELECT * from DB_CORP_CCB.SchCRPCCB.PES
WHERE PesIdf = 153927;

SELECT * from DB_CORP_CCB.SchCRPCCB.PESATVPRF
WHERE PesIdf = 3163

-- POSTO / GRADUAÇÃO:
SELECT 
	PES.Pesidf, GRPACS.GrpAcsCod, GRPACSRGA.GrpAcsRgaNom, GRPACSRGA.GrpAcsRgaAtvIdc, VW_UOR.Uor AS UorCod, PES.PesCpfMigNum, RHCB.POSCOD, RHCB.POS_GRAD, PES.PesNom
FROM DB_MA.SchMA.GRPACSRGAPOS AS GRPACSRGAPOS
INNER JOIN DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK) ON GRPACSRGA.GrpAcsRgaCod = GRPACSRGAPOS.GrpAcsRgaCod
INNER JOIN DB_MA.SchMA.GRPACS AS GRPACS WITH(NOLOCK) ON GRPACS.GrpAcsCod = GRPACSRGA.GrpAcsCod
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON RHCB.POSCOD = GRPACSRGAPOS.PosCod AND RHCB.SLGCOD IN (1,2,3)
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ))
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ VW_UOR ON RHCB.OPM_ATUAL = VW_UOR.UorOpm
WHERE GRPACSRGA.GrpAcsRgaCod = 22 
	AND GRPACSRGAPOS.GrpAcsRgaPosAtvIdc = 1 -- Regra Uor ativa
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1 -- Regra de acesso ativa
	AND VW_UOR.UorOpmAtvIdc = 1 -- Uor Ativa
	AND PES.PesIdf IS NOT NULL
;
--5865
-- FUNÇÃO PESSOA:
SELECT 
	PES.Pesidf, GRPACS.GrpAcsCod, GRPACSRGA.GrpAcsRgaNom, GRPACSRGA.GrpAcsRgaAtvIdc, VW_UOR.Uor, PES.PesCpfMigNum, RHCB.POSCOD, RHCB.POS_GRAD, PES.PesNom
FROM DB_MA.SchMA.GRPACSRGAFUN AS GRPACSRGAFUN
INNER JOIN DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK) ON GRPACSRGA.GrpAcsRgaCod = GRPACSRGAFUN.GrpAcsRgaCod
INNER JOIN DB_MA.SchMA.GRPACS AS GRPACS WITH(NOLOCK) ON GRPACS.GrpAcsCod = GRPACSRGA.GrpAcsCod
INNER JOIN DB_RHCB.SchRH.EFECBFUN AS EFECBFUN ON EFECBFUN.FunCod = GRPACSRGAFUN.FunCod
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesIdf = EFECBFUN.PesIdf
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ) AND RHCB.SLGCOD IN (1,2, 3))
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ VW_UOR ON RHCB.OPM_ATUAL = VW_UOR.UorOpm
WHERE GRPACSRGA.GrpAcsRgaCod = 22
	AND GRPACSRGAFUN.GrpAcsRgaFunAtvIdc = 1 -- Regra Uor ativa
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1 -- Regra de acesso ativa
	AND VW_UOR.UorOpmAtvIdc = 1 -- Uor Ativa
	AND PES.PesIdf IS NOT NULL
;

-- SERVIÇO DA OPM:
SELECT 
	*
FROM DB_MA.SchMA.GRPACSRGASRVTIP AS GRPACSRGASRVTIP
INNER JOIN DB_MA.SchMA.GRPACSRGA AS GRPACSRGA WITH(NOLOCK) ON GRPACSRGA.GrpAcsRgaCod = GRPACSRGASRVTIP.GrpAcsRgaCod
INNER JOIN DB_MA.SchMA.GRPACS AS GRPACS WITH(NOLOCK) ON GRPACS.GrpAcsCod = GRPACSRGA.GrpAcsCod
INNER JOIN DB_MUNICIPIO_OPM.SchUOR.UORSRV AS UORSRV ON UORSRV.SrvTipCod = GRPACSRGASRVTIP.SrvTipCod
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ VW_UOR ON VW_UOR.Uor = UORSRV.UorCod
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON RHCB.OPM_ATUAL = VW_UOR.UorOpm AND RHCB.SLGCOD IN (1,2,3)
LEFT JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ))
WHERE GRPACSRGA.GrpAcsRgaCod = 22
	AND GRPACSRGASRVTIP.GrpAcsRgaSrvTipAtvIdc = 1 -- Regra Uor ativa
	AND GRPACSRGA.GrpAcsRgaAtvIdc = 1 -- Regra de acesso ativa
	AND VW_UOR.UorOpmAtvIdc = 1 -- Uor Ativa
;

/* ------------------------------------------------------------------------------------------------------------------------------------------------- */    
    
-- SELECT VIANA    
DECLARE @CPF VARCHAR(11) = 33945261821--32263773886--33945261821--32321548835--'35974496892' --36799120800 
--
SELECT *--PES.PesIdf, PES.PesNom, PES.PesSclNom, PES.PesTipCod, PES.PesNasDat, RHCB.RE, RHCB.DGT, RHCB.NOME_GUERRA, RHCB.POS_GRAD, UOR.Uor, UOR.UorOpmCod,*
FROM DB_CORP_CCB.SchCRPCCB.PES PES 
LEFT JOIN DB_RHCB.SchRH.RHCB RHCB ON PES.PesCpfMigNum = CAST(RHCB.CPF AS BIGINT) AND (EXISTS (SELECT CPF FROM DB_RHCB.SchRH.RHCB GROUP BY CPF HAVING COUNT(CPF) > 1 ) AND RHCB.SLGCOD IN (1,2, 3))
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ UOR ON RHCB.OPM_ATUAL = uor.UorOpm --AND opm.UniAlcTipCod = 2 
WHERE
PES.PesCpfMigNum =  CAST(@CPF AS BIGINT)

/* ------------------------------------------------------------------------------------------------------------------------------------------------- */

