SELECT * from [DB_CARGA_SIOPM].[SchNOC].[VW_ZELLO]

SELECT * from DB_CARGA_SIOPM.SchNOC.OCR OCR

SELECT * from DB_CARGA_SIOPM.SchNOC.ALE ALE

SELECT * from DB_CARGA_SIOPM.dbo.NAT NAT

SELECT DISTINCT
	CAST(OCR.OcrDat AS DATE) DATA_OCR, 
	PTRDSL.PtrDslHD DESPACHO,
	OCR.OcrNum TALAO, 
	CASE 
		WHEN LEFT(ALE.AleOpmCod,5) = '70101'THEN '1.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70102'THEN '2.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70103'THEN '3.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70104'THEN '4.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70105'THEN '5.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70108'THEN '8.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70117'THEN '17.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70118'THEN '18.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70000'THEN 'GAED'
		WHEN LEFT(ALE.AleOpmCod,5) = '70307'THEN '7.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70315'THEN '15.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70316'THEN '16.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70319'THEN '19.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70409'THEN '9.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70410'THEN '10.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70413'THEN '13.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70414'THEN '14.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70420'THEN '20.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70501'THEN 'GBMar'
		WHEN LEFT(ALE.AleOpmCod,5) = '70506'THEN '6.GB'
		WHEN LEFT(ALE.AleOpmCod,5) = '70511'THEN '11.GB'
		ELSE NULL END AS GB,
	CONCAT(RTRIM(LTRIM(OCR.LgrNom)),', ',RTRIM(LTRIM(OCR.OcrImvNum)),' - ',RTRIM(LTRIM(OCR.OcrBaiNom)),' - ',RTRIM(LTRIM(MUN.MunNom)), ' - ', RTRIM(LTRIM(OCR.OcrRefEnd))) AS ENDERECO,
	RTRIM(LTRIM(OCR.OcrNatIni)) + ' - ' + RTRIM(NAT.NatDes) +' - ' + RTRIM(ALE.AleCplNatDes) + ' - ' + RTRIM(ALE.AleDtlCplNatDes) NATUREZA,
	ALE.AleLon AS LONG, 
	ALE.AleLat AS LAT,
	RTRIM(LTRIM(PTRDSL.PtrIdf)) US_PFX,
	CONCAT(UPPER (CAST ((
		SELECT RTRIM(HISOCOR.HisOcrDes) + ';'
                        FROM DB_CARGA_SIOPM.SchNOC.HISOCR AS HISOCOR
                        WHERE HISOCOR.OcrNum = OCR.OcrNum
                                AND HISOCOR.OcrDat = OCR.OcrDat AND HISOCOR.CadCod = OCR.CadCod
                        ORDER BY HISOCOR.HisOcrSeq ASC
						FOR XML PATH('')
						) AS VARCHAR(MAX))),' TELEFONE SOLICITANTE: (',ocr.TelDddNum,') ',OCR.OcrChmTel ) AS HISTORICO
FROM
	DB_CARGA_SIOPM.SchNOC.OCR OCR
INNER JOIN 
	DB_CARGA_SIOPM.SchNOC.ALE ALE 
	ON OCR.OcrDat = ALE.OcrDat AND OCR.OcrNum = ALE.OcrNum AND OCR.CadCod = ALE.CadCod
LEFT JOIN
	DB_MUNICIPIO_OPM.dbo.MUN MUN ON OCR.OcrMunCod = MUN.Muncod
INNER JOIN 
	DB_CARGA_SIOPM.SchNOC.PTRDSL PTRDSL
	ON OCR.OcrDat = PTRDSL.OcrDat AND OCR.OcrNum = PTRDSL.OcrNum AND OCR.CadCod = PTRDSL.CadCod 
	AND PTRDSL.PtrDslHD >= DATEADD (MINUTE, -1,GETDATE())
	AND PTRDSL.PtrDslHSF = '1753-01-01 00:00:00.000' 
	AND PTRDSL.PtrDslHCF = '1753-01-01 00:00:00.000'
LEFT JOIN 
	DB_CARGA_SIOPM.SchNOC.PTR PTR
	ON RTRIM(LTRIM(PTRDSL.PtrIdf)) = RTRIM(LTRIM(PTR.PtrIdf))LEFT JOIN
	DB_CARGA_SIOPM.dbo.NAT NAT
	ON OCR.OcrNatIni = NAT.NATCOD