SELECT
	CONVERT (DATE, GETDATE()) AS DATA,
	S.StdCod AS CODIGO_SOLICITACAO,
	S.StdDat AS DATA_SOLICITACAO,
	P.PesNom AS SOLICITANTE,
	T.StdNatIcnNom AS NATUREZA,
	N.StdNcdIcnNom AS TIPO,
	L.StdLocLgrNom AS ENDERECO,
	L.StdLocLgrNum AS NUMERAL,
	L.StdLocLgrBaiNom AS BAIRRO,
	L.StdLocLgrCplDes AS COMPLEMENTO,
	M.MunNom AS MUNICIPIO,
        STDOCRSIO.StdOcrSioVinDat,
	CONCAT (
		'http://maps.google.com/maps?q=',
		L.StdLocLat,
		', ',
		L.StdLocLng
	) AS PONTO_EXATO,
	CONCAT (
		'http://maps.google.com/maps?q=',
		L.StdLocPrxLat,
		', ',
		StdLocPrxLng
	) AS PONTO_PROXIMO,
	CONCAT (
		'http://maps.google.com/maps?q=',
		L.StdLocSltLat,
		', ',
		StdLocSltLng
	) AS PONTO_SOLICITACAO,
	O.OcrNum AS OCORRENCIA,
	O.CadCod AS CAD,
	CONCAT (
		'http://prdwiang.ccb.policiamilitar.sp.gov.br/ImgApp/',
		A.StdArdEnd
	) AS IMAGEM
FROM
	COBOM_ONLINE.SchCOBONL.STD S
INNER JOIN COBOM_ONLINE.SchCOBONL.STDLOC L ON S.StdCod = L.StdCod
AND S.StdDat = L.StdDat
INNER JOIN COBOM_ONLINE.SchCOBONL.STDARQ A ON S.StdCod = A.StdCod
AND S.StdDat = A.StdDat
INNER JOIN COBOM_ONLINE.SchCOBONL.STDOCRSIO O ON S.StdCod = O.StdCod
AND S.StdDat = O.StdDat
INNER JOIN COBOM_ONLINE.SchCOBONL.STDNCDICN N ON S.NcdCod = N.NcdCod
INNER JOIN COBOM_ONLINE.SchCOBONL.STDNATICN T ON N.StdNatIcnCod = T.StdNatIcnCod
INNER JOIN DB_CORP_CCB.SchCRPCCB.PES P ON S.PesIdf = P.PesIdf
INNER JOIN DB_MUNICIPIO_OPM.dbo.MUN M ON L.MunCod = M.MunCod
INNER JOIN COBOM_ONLINE.SchCOBONL.STDOCRSIO AS STDOCRSIO WITH(NOLOCK) ON S.StdCod = STDOCRSIO.StdCod AND S.StdDat = STDOCRSIO.StdDat
ORDER BY
	S.StdDat DESC,
	S.StdCod DESC