
SELECT 
	STD.StdCod, STD.StdNum, STD.StdDat, STD.NcdCod, STD.PesIdf, STD.StdIclDat, STD.OpmCbIdf,
	STDOCRSIO.OcrNum, STDOCRSIO.CadCod, STDOCRSIO.StdOcrSioVinDat,
	PES.PesSclNom, PES.PesNom,
	CONCAT('http://prdwiang.ccb.policiamilitar.sp.gov.br/ImgApp/', STDARQ.StdArdEnd) AS StdArdEnd,
	TGMSTDSIT.TgmStdSitNom,
	NAT.NatDes 
FROM COBOM_ONLINE.SchCOBONL.STD AS STD WITH(NOLOCK)
INNER JOIN COBOM_ONLINE.SchCOBONL.STDOCRSIO AS STDOCRSIO WITH(NOLOCK) ON STD.StdCod = STDOCRSIO.StdCod AND STD.StdDat = STDOCRSIO.StdDat
INNER JOIN COBOM_ONLINE.SchCOBONL.STDARQ AS STDARQ WITH(NOLOCK) ON STD.StdCod = STDARQ.StdCod AND STD.StdDat = STDARQ.StdDat
INNER JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES WITH(NOLOCK) ON PES.PesIdf  = STD.PesIdf
INNER JOIN COBOM_ONLINE.SchCOBONL.TGMSTD AS TGMSTD WITH(NOLOCK) ON STD.StdCod = TGMSTD.StdCod AND STD.StdDat = TGMSTD.StdDat
INNER JOIN COBOM_ONLINE.SchCOBONL.TGMSTDSIT AS TGMSTDSIT WITH(NOLOCK) ON TGMSTDSIT.TgmStdSitCod = TGMSTD.TgmStdSitCod AND TGMSTDSIT.TgmStdSitCod = TGMSTD.TgmStdSitCod
INNER JOIN COBOM_ONLINE.SchOPR.NCD AS NCD WITH(NOLOCK) ON NCD.NCDCOD = STD.NcdCod 
INNER JOIN COBOM_ONLINE.SchOPR.NAT AS NAT WITH(NOLOCK) ON NAT.NATCOD = NCD.NATCOD 
WHERE STD.StdDat = (SELECT CONVERT(date, GETDATE()))
ORDER BY STDOCRSIO.StdOcrSioVinDat DESC, STDOCRSIO.OcrNum DESC;

