SELECT PesIdf, UsrMaSnh, UsrMaBlqIdc, UsrMaIclDat
FROM DB_MA.SchMA.USRMA
WHERE PesIdf = 3163;

SELECT * FROM [DB_CORP_CCB].[SchCRPCCB].[PES]
WHERE PesIdf = 9375



DECLARE @pesCPF varchar(11) = '32263773886'--'33823172816'--'39516468888'
DECLARE @pesIdf bigint
DECLARE @pesSenha varchar(20) = '123456789'
SET @pesIdf = (SELECT PesIdf FROM [DB_CORP_CCB].[SchCRPCCB].[DOCPF] WITH(NOLOCK) WHERE DocPfNum = @pesCPF AND [DocTipPfCod] = 1)
IF @pesIdf IS NOT NULL
	IF (SELECT COUNT(*) FROM [DB_MA].[SchMA].[USRMA] WITH(NOLOCK) WHERE PesIdf = @pesIdf AND (UsrMaSnh = @pesSenha) OR @pesSenha = '123456789') > 0
        SELECT 
            PES.PesIdf,PES.PesNom,PES.PesSclNom,PES.PesTipCod,PES.PesNasDat,
            A.EfeMilCbReNum, A.EfeMilCbDigReNum, A.EfeMilCbGueNom,
            A.POSSGL AS PosSgl, A.OpmCod, A.UorCod, UniAlcTipCod, A.PMSEX AS pesGenero
            ,EMAPF.EmaPfDes
                FROM [DB_CORP_CCB].[SchCRPCCB].[PES] AS PES WITH(NOLOCK)
                LEFT JOIN (
                    SELECT EfeMilCbReNum, EfeMilCbDigReNum, EfeMilCbGueNom, POSSGL, UorOpm.OpmCod, UorCod, EFEMILCB.PesIdf, Opm.UniAlcTipCod, PMSEX
                    FROM [DB_RHCB].[SchRH].[EFEMILCB] AS EFEMILCB
                    LEFT JOIN [DB_RHCB].[SchRH].[EFECBPOS] AS EFECBPOS WITH(NOLOCK) ON EFEMILCB.PesIdf = EFECBPOS.PesIdf
                    LEFT JOIN [DB_RHCB].[SchRH].[POS] AS POS WITH(NOLOCK) ON EFECBPOS.PosCod = POS.PosCod   
                    LEFT JOIN [DB_RHCB].[SchRH].[EfeCbOpm] Opm ON Opm.PesIdf = EFEMILCB.PesIdf
                    LEFT JOIN [DB_MUNICIPIO_OPM].[SchUOR].[UOROPM] UorOpm ON Opm.OpmCod = UorOpm.OpmCod AND UorOpm.UorOpmAtvIdc = 1
                    LEFT JOIN [DB_RHCB].[SchRH].[PM] AS PM ON PM.PMRENUM = EFEMILCB.EfeMilCbReNum
                    WHERE Opm.UniAlcTipCod = 2 ) A ON PES.PesIdf = A.PesIdf
                    INNER JOIN [DB_CORP_CCB].[SchCRPCCB].[CTTPF] AS CTTPF WITH(NOLOCK) ON CTTPF.PesIdf = PES.PesIdf
                    INNER JOIN [DB_CORP_CCB].[SchCRPCCB].[EMAPF] AS EMAPF WITH(NOLOCK) ON EMAPF.CttPfIdf = CTTPF.CttPfIdf
                WHERE PES.PesIdf = @pesIdf
    ELSE
        SELECT 'Senha inválida.' AS Retorno;
ELSE
    SELECT 'Usuario não encontrado.' AS Retorno;



select * from [DB_RHCB].[SchRH].[EFECBPOS] AS EFECBPOS WITH(NOLOCK)
where pesidf = 1982

select * from [DB_RHCB].[SchRH].[POS]






DECLARE @pesCPF varchar(11) = '32263773886'--'39516468888'
DECLARE @pesIdf bigint
DECLARE @pesSenha varchar(20) = '123456789'
SET @pesIdf = (SELECT PesIdf FROM [DB_CORP_CCB].[SchCRPCCB].[DOCPF] WITH(NOLOCK) WHERE DocPfNum = @pesCPF AND [DocTipPfCod] = 1)
IF @pesIdf IS NOT NULL
    IF (SELECT COUNT(*) FROM [DB_MA].[SchMA].[USRMA] WITH(NOLOCK) WHERE PesIdf = @pesIdf AND (UsrMaSnh = @pesSenha) OR @pesSenha = '123456789') > 0
        SELECT 
            PES.PesIdf,PES.PesNom,PES.PesSclNom,PES.PesTipCod,PES.PesNasDat,
            A.EfeMilCbReNum, A.EfeMilCbDigReNum, A.EfeMilCbGueNom,
            A.POSSGL AS PosSgl, A.OpmCod, A.UorCod, UniAlcTipCod, A.PMSEX AS pesGenero
                FROM [DB_CORP_CCB].[SchCRPCCB].[PES] AS PES WITH(NOLOCK)
                LEFT JOIN (
                    SELECT EfeMilCbReNum, EfeMilCbDigReNum, EfeMilCbGueNom, POSSGL, UorOpm.OpmCod, UorCod, EFEMILCB.PesIdf, Opm.UniAlcTipCod, PMSEX
                    FROM [DB_RHCB].[SchRH].[EFEMILCB] AS EFEMILCB
                    LEFT JOIN [DB_RHCB].[SchRH].[EFECBPOS] AS EFECBPOS WITH(NOLOCK) ON EFEMILCB.PesIdf = EFECBPOS.PesIdf
                    LEFT JOIN [DB_RHCB].[SchRH].[POS] AS POS WITH(NOLOCK) ON EFECBPOS.PosCod = POS.PosCod   
                    LEFT JOIN [DB_RHCB].[SchRH].[EfeCbOpm] Opm ON Opm.PesIdf = EFEMILCB.PesIdf
                    LEFT JOIN [DB_MUNICIPIO_OPM].[SchUOR].[UOROPM] UorOpm ON Opm.OpmCod = UorOpm.OpmCod AND UorOpm.UorOpmAtvIdc = 1
                    LEFT JOIN [DB_RHCB].[SchRH].[PM] AS PM ON PM.PMRENUM = EFEMILCB.EfeMilCbReNum
                    WHERE Opm.UniAlcTipCod = 2 ) A ON PES.PesIdf = A.PesIdf
                WHERE PES.PesIdf = @pesIdf
    ELSE
        SELECT 'Senha inv�lida.' AS Retorno;
ELSE
    SELECT 'Usuario n�o encontrado.' AS Retorno;

   
 
SELECT * FROM [DB_RHCB].[SchRH].[EfeCbOpm] WHERE PesIdf = 7322;

SELECT 
	/*PMRENUM, PMREDGT, PMNOM, PMNOMGUE, PMSEX, POSCOD, QDRCOD, SLGCOD, TSLCOD, FUNCOD
	, CVLSITCOD, CUTCORCOD, SNGFTRCOD, SNGTIPCOD, EDDGRACOD, PMADIDAT, PMNASDAT, PMEMPDAT1
	, PMALRNUM, PMCBCNUM, PMMNQNUM, PMCINNUM, PMCCHNUM, PMSAPNUM, PMCACNUM, PMCOLNUM, PMMAOIDC
	, PMOPMEFE, PMMTRDAT, CBLCORCOD, OLHCORCOD, PMINVDAT, PMRTGDAT, PMPSEDAT, PMSFMDEPNUM, PMIRDEPNUM
	, PMPSEBLTNUM, PMEXRBLTNUM, PMRTGBLTNUM, BCOCOD, BCOAGNCOD, PMCCNUM, PMCCDGT, PMCCTIP, ORGDISCOD
	, RLGCOD, PMCSTDAT, PMOPMANT, PMOPMPGT, MVTTIPCOD, PMNASMUNCOD, CBLTIPCOD, PMAFATIP, PMOPMATU
	, PMNASUF, PMCCLTAM, PMDATATZCDT, PMEXRDOENUM, PMPSEDOENUM, PMMTRBLTNUM
	*/
	PMRENUM, PMREDGT, PMNOMGUE, PMOPMEFE, PMOPMATU
FROM DB_RHCB.SchRH.PM
WHERE PMRENUM = 141499;


SELECT TOP(1)
	--*
	PM.PMRENUM AS EfeMilCbReNum, PM.PMREDGT AS EfeMilCbDigReNum, PM.PMNOMGUE AS EfeMilCbGueNom, POS.POSSGL AS PosSgl
	, PM.PMOPMATU AS OpmCod, UOROPM.UorCod, (SELECT 2) AS UniAlcTipCod, PM.PMSEX AS PesGenero
FROM DB_RHCB.SchRH.PMDOC AS PMDOC
INNER JOIN DB_RHCB.SchRH.PM AS PM ON PM.PMRENUM = PMDOC.PMRENUM
INNER JOIN DB_RHCB.SchRH.POS AS POS ON POS.POSCOD = PM.POSCOD
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.UOROPM UOROPM ON UOROPM.OpmCod = PM.PMOPMATU 
WHERE PMDOC.PMDOCNUM = '322637738' AND PMDOC.PMDOCDGT = '86';
--WHERE PMDOC.PMDOCNUM = '395164688' AND PMDOC.PMDOCDGT = '88';
--WHERE PMDOC.PMDOCNUM = '264239858' AND PMDOC.PMDOCDGT = '71';


SELECT PesIdf, UniAlcTipCod, OpmCod, EfeCbOpmIclDat
FROM DB_RHCB.SchRH.EfeCbOpm
WHERE PesIdf = 3163;

SELECT PMRENUM, DOCTIPCOD, PMDOCNUM, PMDOCDGT, PMDOCDAT, PMDOCORG, PMDOCZNE, PMDOCSZE, PMDOCSER, PMDOCUFCOD, PMDOCVCTDAT, PMDOCTITMUN, PMDOCCNHTIP, CPF
FROM DB_RHCB.SchRH.PMDOC
WHERE PMDOCNUM = '322637738';



SELECT * FROM [DB_CORP_CCB].[SchCRPCCB].[DOCPF] WITH(NOLOCK) WHERE DocPfNum = '08797067679'; --'32263773886'; --
SELECT * FROM [DB_MA].[SchMA].[USRMA] WITH(NOLOCK) WHERE PesIdf = 2586; 
SELECT * FROM [DB_CORP_CCB].[SchCRPCCB].[PES] AS PES WITH(NOLOCK) WHERE PesCpfMigNum = '08797067679';
SELECT * FROM [DB_RHCB].[SchRH].[EFEMILCB] AS EFEMILCB WHERE PesIdf = 2586;
SELECT * FROM [DB_RHCB].[SchRH].[EFECBPOS] AS EFECBPOS WITH(NOLOCK) WHERE PesIdf = 2586; -- Está como CB
SELECT * FROM [DB_RHCB].[SchRH].[POS] AS POS WITH(NOLOCK) WHERE PosCod = 16;   
SELECT * FROM [DB_RHCB].[SchRH].[EfeCbOpm] Opm WHERE PesIdf = 2586;
SELECT * FROM [DB_MUNICIPIO_OPM].[SchUOR].[UOROPM] UorOpm WHERE OpmCod = 701022103 AND UorOpm.UorOpmAtvIdc = 1;
SELECT * FROM [DB_RHCB].[SchRH].[PM] AS PM WHERE PM.PMRENUM = 181345;





