SELECT
	*
FROM COBOM_ONLINE.SchCOBONL.STD AS STD WITH(NOLOCK)
INNER JOIN COBOM_ONLINE.SchCOBONL.HISSTD AS HISSTD WITH(NOLOCK) ON HISSTD.StdCod = STD.StdCod AND HISSTD.StdDat = STD.StdDat 
INNER JOIN COBOM_ONLINE.SchCOBONL.STDLOC AS STDLOC WITH(NOLOCK) ON STDLOC.StdCod = STD.StdCod AND STDLOC.StdDat = STD.StdDat 
INNER JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES WITH(NOLOCK) ON PES.PesIdf = STD.PesIdf
WHERE STD.PesIdf = 106839 and StdIclDat > '2022-05-25 07:59:22.673'
--WHERE STD.PesIdf = 3163 and StdIclDat > '2022-05-25 07:59:22.673' 
ORDER BY STD.StdIclDat DESC;