SELECT ID, PTRIDF, OCORRENCIAID, OCRDAT, QTA, HODOMETROINICIAL, HODOMETROLOCAL, HODOMETROFINAL, HODOMETROMEDIDA, CPF, ADICIONADA, SIOPM, LOCALIZACAO, PtrOpmAtu, PtrMsvCod
FROM DB_SDO.dbo.VIATURAOCORRENCIA
WHERE OCORRENCIAID = 7896955;


SELECT OCRNUM, OCRDAT, CADCOD, SITUACAOID, ENDERECO, ATENDIMENTOTIPOID, ID, STATUSID, DADOSCOMPLEMENTARES, COMANDANTECPF, MOTIVODEVOLUCAO, HOMOLOGADORCPF, DATAFINALIZACAO, DATAHOMOLOGACAO, ENDERECOINICIAL, POSSUIAGUIA, OCRGREDAT, OPMFATO, OPMATENDIMENTO, NATCOD, LOGRADOUROFINAL, NUMEROFINAL, COMPLEMENTOFINAL, BAIRROFINAL, MUNICIPIOIDFINAL, CEPFINAL, HISTORICO, LOGRADOUROINICIAL, NUMEROINICIAL, COMPLEMENTOINICIAL, BAIRROINICIAL, REFERENCIAINICIAL, MUNICIPIOIDINICIAL, SGB, GB, LOCALIZACAOFINAL, COMANDO, PB, LOCALIZACAOINICIAL, OcrChmDat, OcrRstCod
FROM DB_SDO.dbo.OCORRENCIA
WHERE OCRNUM = 9346 AND OCRDAT = '2024-08-09 00:00:00.000';