-- *** PESSOA ***
SELECT 
--*
  	PES.PesIdf , PES.PesNom, PES.PesSclNom, Pes.PesCpfMigNum, PES.PesIclDat 
	, DOCPF.DocPfNum, DOCPF.DocTipPfCod 
	, EFEMILCB.EfeMilCbReNum , EFEMILCB.EfeMilCbGueNom
	, PM.PosCod, POS.POSSGL
	, PM.PMOPMATU, PM.PMNOMGUE 
	, CTTPF.CttPfIdf, CTTPF.CttTipCod
	, TELPF.TelPfDddNum, TELPF.TelPfTelNum, TELPF.TelTipCod
	, EmaPf.EmaPfDes
FROM DB_CORP_CCB.SchCRPCCB.PES AS PES WITH(NOLOCK)
LEFT JOIN DB_RHCB.SchRH.EFEMILCB AS EFEMILCB WITH(NOLOCK) on EFEMILCB.PesIdf = PES.PesIdf
LEFT JOIN DB_RHCB.SchRH.PM AS PM WITH(NOLOCK) ON PM.PMRENUM  = EFEMILCB.EfeMilCbReNum
LEFT JOIN DB_CORP_CCB.SchCRPCCB.DOCPF AS DOCPF WITH(NOLOCK) ON DOCPF.PesIdf  = PES.PesIdf
LEFT JOIN DB_CORP_CCB.SchCRPCCB.CTTPF AS CTTPF WITH(NOLOCK) ON CTTPF.PesIdf  = PES.PesIdf 
LEFT JOIN DB_CORP_CCB.SchCRPCCB.TELPF AS TELPF WITH(NOLOCK) ON CTTPF.CttPfIdf = TELPF.CttPfIdf
LEFT JOIN DB_CORP_CCB.SchCRPCCB.EmaPf AS EmaPf WITH(NOLOCK) ON CTTPF.CttPfIdf = EmaPf.CttPfIdf
LEFT JOIN DB_RHCB.SchRH.POS AS POS WITH(NOLOCK) ON POS.POSCOD = PM.POSCOD
--LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.UOR AS UOR with(nolock) ON UOR.UorCod  = 
--
--WHERE PES.PesNom LIKE 'ROMILDO %'
--WHERE EFEMILCB.EfeMilCbReNum = 181345
WHERE PES.PesCpfMigNum = '14132314898'--'32263773886'
--WHERE PES.PesIdf IN(153927);
--where PesNom like '%andre coelho%'
--WHERE CTTPF.CttPfIdf = 977993
AND DOCPF.DocTipPfCod = 1;


SELECT AphCelChvIdfIdf, TelPfIdf, CttPfIdf, AphCelChvIdfLocCod, AphCelChvIdfAphChvCod, AphCelChvIdfAphAuzCod
FROM COBOM_ONLINE.SchCOBONL.APHCELCHVIDF
WHERE CttPfIdf = 977993--7211

SELECT VrfAcsIdf, TelPfIdf, CttPfIdf, VrfAcsCod, VrfAcsIclDat, VrfAcsUsrVdcDat
FROM COBOM_ONLINE.SchCOBONL.VRFACS
WHERE TelPfIdf = 17320

SELECT * from DB_CORP_CCB.SchCRPCCB.TELPF
--where TelPfTelNum = 981147000
WHERE TelPfIdf = 606301;

SELECT * FROM DB_CORP_CCB.SchCRPCCB.EmaPf
WHERE CttPfIdf = 977994;