SELECT
	*
	--PTRIDF, PtrMsvCod, PTRTRNINI, PTRTRNFIM, PTROPMORI, PtrOpmAtu, PTRSTTCOD, GB, OPRTIPCOD, FLAG_US_VTR, ENC_NOME, QTD_VTR, ENC_RE_CPF, QTD_PM_TOTAL, QTD_CEL_PM, QTD_TEN_CEL_PM, QTD_MAJ_PM, QTD_CAP_PM, QTD_1TEN_PM, QTD_2TEN_PM, QTD_ASP_OF_PM, QTD_4CFO_PM, QTD_3CFO_PM, QTD_2CFO_PM, QTD_1CFO_PM, QTD_SUBTEN_PM, QTD_1SGT_PM, QTD_2SGT_PM, QTD_3SGT_PM, QTD_CB_PM, QTD_SD_1C_PM, QTD_SD_2C_PM, QTD_FUNC_CIVIL
FROM DB_CARGA_SIOPM.dbo.VW_US_DISP_ATEND
WHERE PTRIDF = 'ABS06310'
--WHERE PTRIDF = 'VO07204' OR PTRIDF = 'VO07205' 
ORDER BY PtrOpmAtu, PTRIDF
;