SELECT
S.SlcCreVsbIdf
,P.PesIdf
,P.PesNom
,P.PesSclNom
,P.PesCpfMigNum
,E.EldCreNom
,M.MunNom
,CAST(S.EldCreDat AS DATE) EldCreDat
,I.SlcCreSitNom
FROM DB_CRED.SchCREVSB.SLCCREVSB S
INNER JOIN DB_CORP_CCB.SchCRPCCB.PES P ON S.PesIdf = P.PesIdf
INNER JOIN DB_CRED.SchCREVSB.ELDVSB V ON S.SlcCreVsbIdf = V.SlcCreVsbIdf
INNER JOIN DB_CRED.SchCREVSB.ELDCRE E ON V.EldCreCod = E.EldCreCod
INNER JOIN DB_CRED.SchCREVSB.AATVSB A ON S.SlcCreVsbIdf = A.SlcCreVsbIdf
INNER JOIN DB_MUNICIPIO_OPM.dbo.MUN M ON A.MunCod = M.MunCod
INNER JOIN DB_CRED.SchCREVSB.SLCCRESIT I ON S.SlcCreSitCod = I.SlcCreSitCod
WHERE P.PesNom NOT LIKE '%TESTE%' OR P.PesNom NOT LIKE '%TERTE%' 