SELECT
	--*
	QdrAvs.QdrAvsIdf, QdrAvs.QdrAvsAss
	, CienAvs.CienAvsDate, CienAvs.ExibQdrAvs
	, POS.POSSGL
	, PM.PMRENUM, PM.PMREDGT 
	, PES.PesIdf, PES.PesNom
	, UORHRQ.UorOpmNome, UORHRQ.UorNome
	, PM.PMOPMEFE, PM.PMOPMATU
FROM DB_QUADRO_AVISOS.SchQDRAVS.CienAvs AS CienAvs
INNER JOIN DB_QUADRO_AVISOS.SchQDRAVS.QdrAvs AS QdrAvs ON QdrAvs.QdrAvsIdf = CienAvs.QdrAvsIdf 
INNER JOIN DB_CORP_CCB.SchCRPCCB.PES AS PES ON PES.PesIdf = CienAvs.PesIdf
LEFT JOIN DB_RHCB.SchRH.EFEMILCB AS EFEMILCB WITH(NOLOCK) on EFEMILCB.PesIdf = PES.PesIdf
LEFT JOIN DB_RHCB.SchRH.PM AS PM WITH(NOLOCK) ON PM.PMRENUM  = EFEMILCB.EfeMilCbReNum
LEFT JOIN DB_RHCB.SchRH.POS AS POS WITH(NOLOCK) ON POS.POSCOD = PM.POSCOD
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.UOROPM AS UOROPM ON UOROPM.OpmCod  = PM.PMOPMATU
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ AS UORHRQ ON UORHRQ.Uor = UOROPM.UorCod
WHERE UORHRQ.UorOpmAtvIdc = 1
ORDER BY QdrAvs.QdrAvsIdf ASC, CienAvs.CienAvsDate DESC;







SELECT QdrAvsIdf, QdrAvsDesc, QdrAvDateIni, QdrAvDateFim, QdrAvDateCad, QdrAvsPesIdf, QdrAvsAtvIdc, QdrAvsGlbIdc, QdrAvsAss
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvs;

SELECT
	*
FROM DB_QUADRO_AVISOS.SchQDRAVS.CienAvs AS CienAvs

SELECT QdrAvsUor, QdrAvsIdf, UorCod
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsUor;

SELECT QdrAvsAtvTipIdf, QdrAvsIdf, AtvTipCod
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsAtvTip;

SELECT QdrAvsAtvPrfIdf, QdrAvsIdf, AtvPrfCod
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsAtivPrf;

SELECT QdrAvsFunIdf, QdrAvsIdf, FUNCOD
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsFun;

SELECT QdrAvsPesIdf, QdrAvsIdf, PesIdf
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsPes;

SELECT QdrAvsPosIdf, QdrAvsIdf, POSCOD
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsPos;

SELECT QdrAvsUorSrvIdf, QdrAvsIdf, SrvTipCod
FROM DB_QUADRO_AVISOS.SchQDRAVS.QdrAvsUorSrv;

