SELECT DISTINCT
	PATRULHACOMPOSICAO.*
	,PTR.PTRSRVCOD
	,PTR.PTRSTTCOD
	,PTR.PtrMsvCod
	,PTR.PtrOpmAtu
	,PTR.PTROPMORI
	,PTR.PTRCABNUM
	,PTR.PTRCABDES
	,PTR.PtrMsvCod
	,OPM.OpmApe OPM_NOME
	,OPM.OPMN06DES OPM_EB
	,OPM.OPMN05DES OPM_PB
	,OPM.OPMN04DES OPM_SGB
	,OPM.OPMN03DES OPM_GB
	,OPM.OPMN02DES OPM_CMD
	,UOR.Uor UorCod
	,UOR.UorNome UorNome
	--,UOR.UorSGBOpmCOD
	--,UOR.UorSGBNome
	--,UOR.UorGBNome
	--,UOR.UorCMNome
FROM
	(
	SELECT
		CADCOD,
		PTRIDF,
		PTRCPNDATINI,
		PTRCPNDATFIM,
		SUM(CASE WHEN ptrcpnposcod =  0 and LTRIM(RTRIM(PTRIDF)) = LTRIM(RTRIM(PTRCPNVTRPFX)) and PTRCPNTITFLG = 'S' THEN 1 ELSE 0 END) AS FLAG_US_VTR,  --FLAG QUE VERIFICA SE O NOME DA US È IGUAL AO PREFIXO DA VIATURA  
		MAX(CASE WHEN PTRCPNTITFLG = 'S' and PTRCPNPOSCOD <> 0 THEN LTRIM(RTRIM(PTRCPNPOSSGL))+ ' '+ PTRCPNDES ELSE NULL END) AS ENC_NOME,  
		MAX(CASE WHEN PTRCPNTITFLG = 'S' and PTRCPNPOSCOD = 0 THEN LTRIM(RTRIM(PTRCPNVTRPFX)) ELSE NULL END) AS VTRPFX, 
		MAX(CASE WHEN PTRCPNTITFLG = 'S' and PTRCPNPOSCOD <> 0 THEN LTRIM(RTRIM(PTRCPNCOD)) ELSE NULL END) AS ENC_RECPF,  
		SUM(CASE WHEN PTRCPNPOSCOD =  0  THEN 1 ELSE 0 END) AS QTD_VTR,  
		SUM(CASE WHEN PTRCPNPOSCOD <> 0  THEN 1 ELSE 0 END) AS QTD_PMTOTAL,  
		SUM(CASE WHEN PTRCPNPOSCOD =  1  THEN 1 ELSE 0 END) AS QTD_ALSDPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  3  THEN 1 ELSE 0 END) AS QTD_ASPOFPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  4  THEN 1 ELSE 0 END) AS QTD_CAPPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  5  THEN 1 ELSE 0 END) AS QTD_CBPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  8  THEN 1 ELSE 0 END) AS QTD_CELPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  10 THEN 1 ELSE 0 END) AS QTD_FUNCCIVIL,  
		SUM(CASE WHEN PTRCPNPOSCOD =  11 THEN 1 ELSE 0 END) AS QTD_MAJPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  15 THEN 1 ELSE 0 END) AS QTD_SDPM2C,  
		SUM(CASE WHEN PTRCPNPOSCOD =  16 THEN 1 ELSE 0 END) AS QTD_SDPM1C,  
		SUM(CASE WHEN PTRCPNPOSCOD =  18 THEN 1 ELSE 0 END) AS QTD_SUBTENPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  20 THEN 1 ELSE 0 END) AS QTD_TENCELPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  22 THEN 1 ELSE 0 END) AS QTD_1SGTPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  23 THEN 1 ELSE 0 END) AS QTD_1TENPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  24 THEN 1 ELSE 0 END) AS QTD_2SGTPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  25 THEN 1 ELSE 0 END) AS QTD_2TENPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  26 THEN 1 ELSE 0 END) AS QTD_3SGTPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  27 THEN 1 ELSE 0 END) AS QTD_SPOSTGRAD,  
		SUM(CASE WHEN PTRCPNPOSCOD =  29 THEN 1 ELSE 0 END) AS QTD_3CFOPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  30 THEN 1 ELSE 0 END) AS QTD_2CFOPM,  
		SUM(CASE WHEN PTRCPNPOSCOD =  31 THEN 1 ELSE 0 END) AS QTD_1CFOPM
	FROM
		DB_CARGA_SIOPM.dbo.PTRCPN WITH(NOLOCK)
	WHERE
		GETDATE() BETWEEN PTRCPNDATINI AND PTRCPNDATFIM
	GROUP BY
		CADCOD,
		PTRIDF,
		PTRCPNDATINI,
		PTRCPNDATFIM
	)PATRULHACOMPOSICAO
LEFT JOIN DB_CARGA_SIOPM.dbo.PTR PTR WITH(NOLOCK) ON 
	PATRULHACOMPOSICAO.CADCOD = PTR.CADCOD AND
	PATRULHACOMPOSICAO.PTRIDF = PTR.PTRIDF AND
	PATRULHACOMPOSICAO.PTRCPNDATINI = PTR.PTRTRNINI AND
	PATRULHACOMPOSICAO.PTRCPNDATFIM = PTR.PTRTRNFIM
--LEFT JOIN DB_CARGA_SIOPM.dbo.VW_COMPOSICAO_US COMP WITH(NOLOCK) ON 
--	PATRULHACOMPOSICAO.PTRIDF = COMP.PTRIDF
LEFT JOIN (SELECT * FROM DB_MUNICIPIO_OPM.dbo.OPM WITH (NOLOCK) WHERE LEFT(OPMCOD,1) = 7) OPM  ON 
	PTR.PtrOpmAtu = OPM.OPMCOD 
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ UOR WITH (NOLOCK) ON 
	PTR.PtrOpmAtu = UOR.UorOpm AND UOR.UorOpmAtvIdc = 1
WHERE 
	PTR.PTRSRVCOD = 3
ORDER BY 
	PATRULHACOMPOSICAO.PTRIDF