SELECT OCRNUM, OCRDAT, CADCOD, SITUACAOID, ENDERECO, ATENDIMENTOTIPOID, ID, STATUSID, DADOSCOMPLEMENTARES, COMANDANTECPF, MOTIVODEVOLUCAO, HOMOLOGADORCPF, DATAFINALIZACAO, DATAHOMOLOGACAO, ENDERECOINICIAL, POSSUIAGUIA, OCRGREDAT, OPMFATO, OPMATENDIMENTO, NATCOD, LOGRADOUROFINAL, NUMEROFINAL, COMPLEMENTOFINAL, BAIRROFINAL, MUNICIPIOIDFINAL, CEPFINAL, HISTORICO, LOGRADOUROINICIAL, NUMEROINICIAL, COMPLEMENTOINICIAL, BAIRROINICIAL, REFERENCIAINICIAL, MUNICIPIOIDINICIAL, SGB, GB, LOCALIZACAOFINAL, COMANDO, PB, LOCALIZACAOINICIAL, OcrChmDat, OcrRstCod
FROM DB_SDO.dbo.OCORRENCIA
WHERE ID = 8304714
;

SELECT OcrDat, OcrNum, CadCod, HisOcrCod, HisOcrNum, HisOcrSeq, HisOcrDes, HisOcrPmReNum, HisOcrDat, OCORRENCIAID
FROM DB_SDO.dbo.HISOCR
WHERE OcrDat = '2024-12-11 00:00:00.000' AND OCRNUM = 14174
;

SELECT ID, PTRIDF, OCORRENCIAID, OCRDAT, QTA, HODOMETROINICIAL, HODOMETROLOCAL, HODOMETROFINAL, HODOMETROMEDIDA, CPF, ADICIONADA, SIOPM, LOCALIZACAO, PtrOpmAtu, PtrMsvCod
FROM DB_SDO.dbo.VIATURAOCORRENCIA
WHERE PTRIDF = 'UR01103' AND OCRDAT = '2024-12-11 00:00:00.000'
;


SELECT ID, VIATURAOCORRENCIAID, GRADUACAO, GRADUACAOCOD, SEQUENCIA, NOMEGUERRA, ENCARREGADO, COMANDANTE, RE, CPF, TIPOPESSOA, OPMATU
FROM DB_SDO.dbo.VIATURAINTEGRANTE
WHERE VIATURAOCORRENCIAID = 6444823
;

SELECT 
	POS_GRAD, NOME, NOME_GUERRA 
--EfetivoIdf, CPF, POSCOD, POS_GRAD, RE, DIG, NOME, NOME_GUERRA, SLGCOD, SITUACAO, SEXO, QDRCOD, QDR, OPMCOD_EFETIVA, OPM_NOME_EFETIVA, OPMCOD_ATUAL, OPM_NOME_ATUAL, OPMCOD_ANTERIOR, OPM_NOME_ANTERIOR, GRD_CMD, BTL, CIA, UORCOD, UOR, DATA_INGRESSO, DATA_POSSE, EST_CVL, ESCOLARIDADE, RELIGIAO, DATA_NASC, CNH, VAL_CNH, CAT_CNH, CELULAR, TEL_FUNCIONAL, EMAIL_FUNCIONAL, EMAIL_PARTICULAR, CODBCO, BANCO, AGENCIA, CONTA, DGT_CONT, ALTURA, TIP_SANG, FTR_SANG, CUTIS, TIP_CBL, COR_CBL, NIVEL, ALMAN, DATA_ULT_PROM
FROM DB_EFETIVO.SchEfetivo.Efetivo
WHERE CPF = '14691677607' OR CPF = '09420212661' OR CPF = '41180603885'
;