SELECT ID, [DATA], [LEVEL], NOMESISTEMA, MESSAGE, STACKTRACE, AMBIENTE
FROM DB_SDO.dbo.LOG
WHERE 
id = 5562351;

SELECT OCRNUM, OCRDAT, CADCOD, SITUACAOID, ENDERECO, ATENDIMENTOTIPOID, ID, STATUSID, DADOSCOMPLEMENTARES, COMANDANTECPF, MOTIVODEVOLUCAO, HOMOLOGADORCPF, DATAFINALIZACAO, DATAHOMOLOGACAO, ENDERECOINICIAL, POSSUIAGUIA, OCRGREDAT, OPMFATO, OPMATENDIMENTO, NATCOD, LOGRADOUROFINAL, NUMEROFINAL, COMPLEMENTOFINAL, BAIRROFINAL, MUNICIPIOIDFINAL, CEPFINAL, HISTORICO, LOGRADOUROINICIAL, NUMEROINICIAL, COMPLEMENTOINICIAL, BAIRROINICIAL, REFERENCIAINICIAL, MUNICIPIOIDINICIAL, SGB, GB, LOCALIZACAOFINAL, COMANDO, PB, LOCALIZACAOINICIAL, OcrChmDat, OcrRstCod
FROM DB_SDO.dbo.OCORRENCIA
WHERE OCRNUM = 14577 AND OCRDAT = '2024-06-13 00:00:00.000';

SELECT ID, PTRIDF, OCORRENCIAID, OCRDAT, QTA, HODOMETROINICIAL, HODOMETROLOCAL, HODOMETROFINAL, HODOMETROMEDIDA, CPF, ADICIONADA, SIOPM, LOCALIZACAO, PtrOpmAtu, PtrMsvCod
FROM DB_SDO.dbo.VIATURAOCORRENCIA
WHERE OCORRENCIAID = 7704308;

SELECT ID, VIATURAOCORRENCIAID, GRADUACAO, GRADUACAOCOD, SEQUENCIA, NOMEGUERRA, ENCARREGADO, COMANDANTE, RE, CPF, TIPOPESSOA, OPMATU
FROM DB_SDO.dbo.VIATURAINTEGRANTE
WHERE VIATURAOCORRENCIAID = 6027054;