SELECT
* 
FROM 
[DB_CARGA_SIOPM].[dbo].[VW_COMPOSICAO_US] 
WHERE RTRIM(LTRIM(INTEGRANTE_VTR)) != 'VIATURA' 
ORDER BY 
GB, PTRIDF, ENCARREGADO DESC


SELECT
	PATRULHA.PTRIDF,
	PATRULHA.PtrMsvCod,
	PATRULHA.PTRTRNINI,
	PATRULHA.PTRTRNFIM,
	PATRULHA.PTROPMORI,
	PATRULHA.PtrOpmAtu,
	PTRSTT.PtrSttDes AS PTRSTTCOD,
	CASE
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70100' THEN 'GAED_FT'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70101' THEN '01.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70102' THEN '02.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70103' THEN '03.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70104' THEN '04.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70105' THEN '05.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70108' THEN '08.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70117' THEN '17.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70118' THEN '18.GB'
--
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70307' THEN '07.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70315' THEN '15.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70316' THEN '16.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70319' THEN '19.GB'
--
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70409' THEN '09.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70410' THEN '10.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70412' THEN '12.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70413' THEN '13.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70414' THEN '14.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70420' THEN '20.GB'
--
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70506' THEN '06.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70511' THEN '11.GB'
		WHEN LEFT(PATRULHA.PtrOpmAtu,5) = '70501' THEN 'GBMAR'
		ELSE NULL 
	END AS GB,
	COMPOSICAO.INTEGRANTE_VTR,
	COMPOSICAO.RE_CPF,
	COMPOSICAO.ENCARREGADO
FROM
(
--
--===========================================================================================================================
-- PATRULHA E TURNO EM CODIGO DE SERVIÇO 3
--===========================================================================================================================
SELECT
	PTR.*
FROM
	(
	SELECT  
		PTR.CADCOD,
		RTRIM(LTRIM(PTR.PTRIDF)) AS PTRIDF,
		PTR.PTRTRNINI,
		PTR.PTRTRNFIM,
		PTR.PTRSRVCOD,
		PTR.PtrMsvCod,
		PTR.PTROPMORI,
		PTR.PtrOpmAtu,
		PTR.PTRSTTCOD,
		PTR.OPRTIPCOD
	FROM 
		DB_CARGA_SIOPM.dbo.PTR PTR WITH(NOLOCK)
	WHERE
		PTR.PTRSRVCOD = 3
		AND
		GETDATE() >= PTR.PTRTRNINI 
		AND
		GETDATE() <= PTR.PTRTRNFIM
	) PTR
INNER JOIN
	(
	SELECT 
		RTRIM(LTRIM(PTR.PTRIDF)) AS PTRIDF,
		MAX(PTRTRNINI) AS TRNINIMAX
	FROM 
		DB_CARGA_SIOPM.dbo.PTR WITH(NOLOCK)
	WHERE
		PTRSRVCOD = 3
		AND
		GETDATE() >= PTRTRNINI 
		AND
		GETDATE() <= PTRTRNFIM
	GROUP BY 
		PTRIDF
	) PTR_MAX 
		ON PTR.PTRIDF = PTR_MAX.PTRIDF
		AND PTR.PTRTRNINI = PTR_MAX.TRNINIMAX
) AS PATRULHA
--
--===========================================================================================================================
-- COMPOSIÇÃO DO EFETIVO DA VTR DO ULTIMO TURNO ATIVO
--===========================================================================================================================
LEFT JOIN
(
SELECT
		B.CADCOD,
		RTRIM(LTRIM(B.PTRIDF)) AS PTRIDF,
		A.INIMAX,
		LTRIM(RTRIM(B.PTRCPNPOSSGL)) + ' ' + B.PTRCPNDES AS INTEGRANTE_VTR, 
		LTRIM(RTRIM(B.PTRCPNCOD)) AS RE_CPF,
		CASE WHEN B.PTRCPNTITFLG = 'S' AND B.PTRCPNPOSCOD != 0 THEN 'ENCARREGADO' ELSE NULL END AS ENCARREGADO
	FROM 
		DB_CARGA_SIOPM.dbo.PTRCPN B WITH(NOLOCK)
	INNER JOIN
	(
		SELECT 
			RTRIM(LTRIM(PTRCPN.PTRIDF)) AS PTRIDF, 
			MAX(PTRCPN.PTRCPNDATINI) AS INIMAX
		FROM 
			DB_CARGA_SIOPM.dbo.PTRCPN WITH(NOLOCK)
		--SÓ PTR DOS BOMBEIROS
		INNER JOIN 
			DB_CARGA_SIOPM.dbo.PTR WITH(NOLOCK) ON RTRIM(LTRIM(PTRCPN.PTRIDF)) = RTRIM(LTRIM(PTR.PTRIDF)) 
			AND PTRCPN.PTRCPNDATINI = PTR.PTRTRNINI AND PTR.PTRSRVCOD = 3
		WHERE
			GETDATE() >= PTRCPN.PTRCPNDATINI 
			AND
			GETDATE() <= PTRCPN.PTRCPNDATFIM
		GROUP BY 
			RTRIM(LTRIM(PTRCPN.PTRIDF)) 
	) AS A  
	ON RTRIM(LTRIM(B.PTRIDF)) = RTRIM(LTRIM(A.PTRIDF))
--
	WHERE
		GETDATE() >= A.INIMAX 
		AND
		GETDATE() <= B.PTRCPNDATFIM
--
) AS COMPOSICAO
ON
	RTRIM(LTRIM(PATRULHA.PTRIDF)) = RTRIM(LTRIM(COMPOSICAO.PTRIDF))
	AND
	PATRULHA.PTRTRNINI = COMPOSICAO.INIMAX
--
--===========================================================================================================================
-- STATUS DAS UNIDADES DE SERVIÇOS
--===========================================================================================================================
LEFT JOIN
	DB_CARGA_SIOPM.dbo.PTRSTT PTRSTT ON PATRULHA.PTRSTTCOD = PTRSTT.PtrSttCod
--
WHERE 
	 COMPOSICAO.INTEGRANTE_VTR IS NOT NULL;
	 
	
SELECT * FROM DB_CARGA_SIOPM.dbo.PTRSTT

SELECT * FROM DB_CARGA_SIOPM.dbo.PTR

SELECT * FROM DB_CARGA_SIOPM.dbo.PTRCPN
ORDER BY PTRCPNDATINI DESC 


		
		
SELECT *
	/*RTRIM(LTRIM(PTRCPN.PTRIDF)) AS PTRIDF, 
	MAX(PTRCPN.PTRCPNDATINI) AS INIMAX*/
FROM 
	DB_CARGA_SIOPM.dbo.PTRCPN WITH(NOLOCK)
--SÓ PTR DOS BOMBEIROS
INNER JOIN 
	DB_CARGA_SIOPM.dbo.PTR WITH(NOLOCK) ON RTRIM(LTRIM(PTRCPN.PTRIDF)) = RTRIM(LTRIM(PTR.PTRIDF)) 
	AND PTRCPN.PTRCPNDATINI = PTR.PTRTRNINI AND PTR.PTRSRVCOD = 3
WHERE
	GETDATE() >= PTRCPN.PTRCPNDATINI 
	ORDER BY PTRCPNDATFIM DESC