SELECT 
	-- * 
	OCRNUM, OCRGREDAT, ENDERECO, PRONTIDAO, PTRIDF, ENCARREGADOFINALCPF, POS_GRAD, RE, NOME_GUERRA, OPMFATO, GB, SGB, EB
FROM DB_SDO.dbo.VW_Talao_pendente
ORDER BY GB, OCRGREDAT;

SELECT * FROM DB_SDO.dbo.LOG WHERE ID = '5445887'