-- Tabela para consultar de Militar Ativo, Agregado e Inativo
SELECT * FROM DB_EFETIVO.SchEfetivo.Efetivo
--WHERE RE = 112087
WHERE CPF = '15739843707'
--WHERE NOME LIKE '%NAVARRO%'

-- Tabela para consultar Militar em qualquer situação e Funcionário Civil cadastrado na Base de Dados da PM 
SELECT * FROM DB_EFETIVO.SchEfetivo.RHCB
WHERE CPF = '08846812891'

SELECT 
	* 
FROM DB_CORP_CCB.SchCRPCCB.PES P --WITH(NOLOCK)
JOIN DB_CORP_CCB.SchCRPCCB.DOCPF DOC ON DOC.PesIdf = P.PesIdf 
WHERE
	--P.PesIdf = 79201
	--DOC.DocPfNum = '92644856000' -- TESTE CADASTRO GOV BR
	--DOC.DocPfNum = '26922090870' --GIUSEPPE (OK)
	--DOC.DocPfNum = '33618090889' --BRUNO (OK)
	--DOC.DocPfNum = '47031718805' --DEIVID (OK)
	--DOC.DocPfNum = '21762773848' --RODRIGO (OK)
	DOC.DocPfNum = '29963124810' 
	AND DOC.DocTipPfCod = 1

SELECT AtvPrfCod, PesIdf, PesAtvPrfIclDat
FROM DB_CORP_CCB.SchCRPCCB.PESATVPRF
WHERE AtvPrfCod = 2;

SELECT AtvPrfCod, AtvPrfNom
FROM DB_CORP_CCB.SchCRPCCB.ATVPRF;





SELECT * FROM DB_CORP_CCB.SchCRPCCB.EmaPf 
WHERE EmaPfDes LIKE '%renan.figueiredo%'


SELECT * FROM DB_CORP_CCB.SchCRPCCB.CTTPF 
WHERE CttPfIdf = 1700359

SELECT * FROM DB_CORP_CCB.SchCRPCCB.PES
WHERE PesIdf = 1450509



SELECT PesIdf, PesNom, PesSclNom, PesTipCod, PesNasDat, PesCpfMigNum, PesIclDat
FROM DB_CORP_CCB.SchCRPCCB.PES
WHERE PesCpfMigNum = '40318984873';
--WHERE PesNom like '%STHEFANY ROITMAN%';

-- *** PESSOA ***
SELECT 
--*
  	PES.PesIdf , PES.PesNom, PES.PesSclNom, Pes.PesCpfMigNum, PES.PesIclDat 
	, DOCPF.DocPfNum, DOCPF.DocTipPfCod 
	, EFEMILCB.EfeMilCbReNum , EFEMILCB.EfeMilCbGueNom
	, PM.PosCod, POS.POSSGL
	, PM.PMOPMATU, PM.PMNOMGUE 
	, CTTPF.CttPfIdf, CTTPF.CttTipCod
	, TELPF.TelPfDddNum, TELPF.TelPfTelNum, TELPF.TelTipCod
	, EmaPf.EmaPfDes
FROM DB_CORP_CCB.SchCRPCCB.PES AS PES WITH(NOLOCK)
LEFT JOIN DB_RHCB.SchRH.EFEMILCB AS EFEMILCB WITH(NOLOCK) on EFEMILCB.PesIdf = PES.PesIdf
LEFT JOIN DB_RHCB.SchRH.PM AS PM WITH(NOLOCK) ON PM.PMRENUM  = EFEMILCB.EfeMilCbReNum
LEFT JOIN DB_CORP_CCB.SchCRPCCB.DOCPF AS DOCPF WITH(NOLOCK) ON DOCPF.PesIdf  = PES.PesIdf
LEFT JOIN DB_CORP_CCB.SchCRPCCB.CTTPF AS CTTPF WITH(NOLOCK) ON CTTPF.PesIdf  = PES.PesIdf 
LEFT JOIN DB_CORP_CCB.SchCRPCCB.TELPF AS TELPF WITH(NOLOCK) ON CTTPF.CttPfIdf = TELPF.CttPfIdf
LEFT JOIN DB_CORP_CCB.SchCRPCCB.EmaPf AS EmaPf WITH(NOLOCK) ON CTTPF.CttPfIdf = EmaPf.CttPfIdf
LEFT JOIN DB_RHCB.SchRH.POS AS POS WITH(NOLOCK) ON POS.POSCOD = PM.POSCOD
--LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.UOR AS UOR with(nolock) ON UOR.UorCod  = 
--
--WHERE PES.PesNom LIKE 'ROMILDO %'
--WHERE EFEMILCB.EfeMilCbReNum = 181345
WHERE PES.PesCpfMigNum = '15739843707'--'32263773886'
--WHERE PES.PesIdf IN(153927);
--where PesNom like '%andre coelho%'
AND DOCPF.DocTipPfCod = 1;

-- *** ATIVIDADES PROFISISONAIS DA PESSOA ***
SELECT AtvPrfCod, AtvPrfNom
FROM DB_CORP_CCB.SchCRPCCB.ATVPRF;

SELECT AtvPrfCod, PesIdf, PesAtvPrfIclDat
FROM DB_CORP_CCB.SchCRPCCB.PESATVPRF
WHERE PesIdf = 108102;

-- *** PESSOA (ANTIGO-SEPARADOS) ***
SELECT 
--*
  PES.PesIdf , PES.PesNom, PES.PesSclNom, Pes.PesCpfMigNum, PES.PesIclDat 
, DOCPF.DocPfNum, DOCPF.DocTipPfCod 
, EFEMILCB.EfeMilCbReNum , EFEMILCB.EfeMilCbGueNom
, PM.PMOPMATU, PM.PMNOMGUE 
--, CTTPF.CttPfIdf, CTTPF.CttTipCod, CTTPF.CttPfIclDat 
FROM DB_CORP_CCB.SchCRPCCB.PES AS PES WITH(NOLOCK)
LEFT JOIN DB_RHCB.SchRH.EFEMILCB AS EFEMILCB WITH(NOLOCK) on EFEMILCB.PesIdf = PES.PesIdf
LEFT JOIN DB_RHCB.SchRH.PM AS PM WITH(NOLOCK) ON PM.PMRENUM  = EFEMILCB.EfeMilCbReNum
LEFT JOIN DB_CORP_CCB.SchCRPCCB.DOCPF AS DOCPF WITH(NOLOCK) ON DOCPF.PesIdf  = PES.PesIdf
--LEFT JOIN DB_CORP_CCB.SchCRPCCB.CTTPF AS CTTPF WITH(NOLOCK) ON CTTPF.PesIdf  = PES.PesIdf 
--LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.UOR AS UOR with(nolock) ON UOR.UorCod  = 
--
--WHERE EFEMILCB.EfeMilCbReNum = 195003
WHERE PES.PesCpfMigNum = '10001213644'--'32263773886'
--WHERE PES.PesCpfMigNum = '09686826009' --BPV
--WHERE PES.PesCpfMigNum = '03110732041' --BRIGADISTA
--WHERE PES.PesIdf IN(8219);'
--where PesNom like '%andre coelho%'
AND DOCPF.DocTipPfCod = 1

-- *** CONTATOS DA PESSOA ***
SELECT CttPfIdf, PesIdf, CttTipCod, CttPfIclDat
FROM DB_CORP_CCB.SchCRPCCB.CTTPF --Id 1: Telefone / Id 2: E-mail / Id 3: Endereço (1753-01-01 00:00:00.000)
WHERE PesIdf IN(562569);

-- *** TELEFONES DA PESSOA ***
SELECT TelPfIdf, CttPfIdf, TelPfDddNum, TelPfTelNum, TelTipCod, TelPfAtvIdc --TelTipCod == 1: Fixo / 2: Celular
FROM DB_CORP_CCB.SchCRPCCB.TELPF
--WHERE CttPfIdf IN (519, 8872, 121344, 121345, 121346, 121347, 121348) and TelTipCod = 2;
WHERE CttPfIdf IN (977887);

-- *** E-MAILS DA PESSOA ***
SELECT EmaPfIdf, CttPfIdf, EmaPfDes, EmaPfAtvIdc
FROM DB_CORP_CCB.SchCRPCCB.EmaPf WITH(NOLOCK)
WHERE CttPfIdf IN(11179);

-- *** CHAVE DO CELULAR DA PESSOA ***
SELECT AphCelChvIdfIdf, TelPfIdf, CttPfIdf, AphCelChvIdfLocCod, AphCelChvIdfAphChvCod, AphCelChvIdfAphAuzCod
FROM COBOM_ONLINE.SchCOBONL.APHCELCHVIDF
--WHERE AphCelChvIdfAphChvCod  = 'A'AND AphCelChvIdfAphAuzCod  = 'A'
WHERE CttPfIdf IN (5725);
--WHERE CttPfIdf IN (7211);

-- *** VERIFICAÇÃO DE ACESSO DA PESSOA ***
SELECT VrfAcsIdf, TelPfIdf, CttPfIdf, VrfAcsCod, VrfAcsIclDat, VrfAcsUsrVdcDat
FROM COBOM_ONLINE.SchCOBONL.VRFACS
WHERE TelPfIdf IN (5725)
--WHERE TelPfIdf IN (17320)
ORDER BY VrfAcsIclDat DESC 
;

/*DELETE FROM DB_CORP_CCB.SchCRPCCB.TELPF
WHERE TelPfIdf = 60898 AND TelPfIdf = 60899 AND TelPfIdf = 60900 

DELETE FROM DB_CORP_CCB.SchCRPCCB.CTTPF
WHERE CttPfIdf = 121345 AND CttPfIdf = 121346 AND CttPfIdf = 121347 
*/


--===================================================================================================================

-- *** E-MAIL ***
SELECT EmaPfIdf, CttPfIdf, EmaPfDes, EmaPfAtvIdc
FROM DB_CORP_CCB.SchCRPCCB.EmaPf
WHERE EmaPfDes LIKE 'salviano.tst@%';



