SELECT 
	--*
	PES.PesIdf, PES.PesNom, PES.PesSclNom 
	, CTTPF.CttPfIdf, CTTPF.CttTipCod 
	, EMAPF.EmaPfIdf, EMAPF.EmaPfDes 
FROM [DB_CORP_CCB].[SchCRPCCB].[PES] AS PES
JOIN [DB_CORP_CCB].[SchCRPCCB].[CTTPF] AS CTTPF ON CTTPF.PesIdf = PES.PesIdf
INNER JOIN [DB_CORP_CCB].[SchCRPCCB].[EMAPF] AS EMAPF ON EMAPF.CttPfIdf = CTTPF.CttPfIdf
LEFT JOIN DB_CORP_CCB.SchCRPCCB.DOCPF AS DOCPF ON DOCPF.PesIdf  = PES.PesIdf
WHERE DOCPF.DocPfNum = '13533547418' AND DOCPF.DocTipPfCod = 1
--WHERE PES.PesIdf = 76438



SELECT 
	*
FROM [DB_CORP_CCB].[SchCRPCCB].[EMAPF] AS EMAPF
WHERE EmaPfIdf = 282895



SELECT EfetivoIdf, CPF, POSCOD, POS_GRAD, RE, DIG, NOME, NOME_GUERRA, SLGCOD, SITUACAO, SEXO, QDRCOD, QDR, OPMCOD_EFETIVA, OPM_NOME_EFETIVA, OPMCOD_ATUAL, OPM_NOME_ATUAL, OPMCOD_ANTERIOR, OPM_NOME_ANTERIOR, GRD_CMD, BTL, CIA, UORCOD, UOR, DATA_INGRESSO, DATA_POSSE, EST_CVL, ESCOLARIDADE, RELIGIAO, DATA_NASC, CNH, VAL_CNH, CAT_CNH, CELULAR, TEL_FUNCIONAL, EMAIL_FUNCIONAL, EMAIL_PARTICULAR, CODBCO, BANCO, AGENCIA, CONTA, DGT_CONT, ALTURA, TIP_SANG, FTR_SANG, CUTIS, TIP_CBL, COR_CBL, NIVEL, ALMAN, DATA_ULT_PROM
FROM DB_EFETIVO.SchEfetivo.Efetivo
WHERE cpf = '12966376708';