SELECT AtvPrfCod, AtvPrfNom
FROM DB_CORP_CCB.SchCRPCCB.ATVPRF;

SELECT
	*
FROM DB_CORP_CCB.SchCRPCCB.PESATVPRF ATV
INNER JOIN DB_CORP_CCB.SchCRPCCB.PES PES ON PES.PesIdf = ATV.PesIdf 
WHERE AtvPrfCod = 2
--AND PesCpfMigNum = '23074675802'
;