--> CARGA ATUAL TRAZIDA DA PM:
SELECT FUCCVLCPF, FUCCVLNOM, FUCCVLSEX, FUCCVLADIDAT, OPMCOD, FUCCVLCPFDGT, CPF, FUCCVLNASDAT, FUCCVLTIP, PrsEmpCod, FunCvlSaiDat, LeiIdf
FROM DB_CARGA_BDCORP.SchBDCORP.FUCCVL
--WHERE FUCCVLCPF LIKE 124758007
WHERE FUCCVLCPF LIKE '%230746758%'
;

DECLARE @CPF VARCHAR(11) =  '17114643845'
DECLARE @CPFPES BIGINT = @CPF
DECLARE @PES BIGINT = 
						(
							SELECT PES.PesIdf 
							FROM DB_CORP_CCB.SchCRPCCB.PES PES  
							LEFT JOIN (SELECT TOP 1 CPF FROM DB_RHCB.dbo.VW_CONSULTA_GERAL WHERE CPF LIKE '%'+@CPF+'%' ORDER BY  DATA_INGRESSO DESC) C 
							ON CAST(C.CPF AS BIGINT) = PES.PesCpfMigNum 
							WHERE PesCpfMigNum LIKE '%'+CAST(@CPFPES AS VARCHAR(11))+'%'
						)
DECLARE @TEL BIGINT = (SELECT CttPfIdf  
								FROM DB_CORP_CCB.SchCRPCCB.CTTPF WHERE PesIdf = @PES AND CttTipCod = 1)
DECLARE @CTTEMAIL BIGINT = (SELECT CttPfIdf FROM DB_CORP_CCB.SchCRPCCB.CTTPF WHERE PesIdf = @PES AND CttTipCod = 2)
-- Consulta da PES
SELECT * FROM DB_CORP_CCB.SchCRPCCB.PES WHERE PesIdf = @PES
-- E-mail Cadastrado na Corp CCB
SELECT * FROM DB_CORP_CCB.SchCRPCCB.EmaPf WHERE CttPfIdf = @CTTEMAIL
-- Telefone Cadastrado na Corp CCB
SELECT * FROM DB_CORP_CCB.SchCRPCCB.TelPf WHERE CttPfIdf = @TEL
-- Id dos Contatos da Corp CCB
SELECT * FROM DB_CORP_CCB.SchCRPCCB.CTTPF WHERE PesIdf = @PES
--Enderecos Cadastrados na Corp CCB
SELECT * FROM DB_CORP_CCB.SchCRPCCB.ENDPF WHERE PesIdf = @PES
-- Documentos Cadastrados na Corp CCB
SELECT * FROM DB_CORP_CCB.SchCRPCCB.DOCPF WHERE PesIdf = @PES
-- Dados  essenciais da Tabela Efetivo
SELECT EfetivoIdf, CPF, POS_GRAD, RE, NOME_GUERRA, EMAIL_FUNCIONAL, EMAIL_PARTICULAR, CELULAR, TEL_FUNCIONAL FROM DB_EFETIVO.SchEfetivo.Efetivo WHERE CPF LIKE '%'+CAST(@CPFPES AS VARCHAR(11))+'%'
-- Dados essenciais da RHCB
SELECT * FROM DB_EFETIVO.SchEfetivo.RHCB WHERE CPF LIKE '%'+@CPF+'%'
-- OPM Efetiva / Atual
SELECT * FROM DB_RHCB.SchRH.EfeCbOpm WHERE PesIdf = @PES;




