
SELECT 
        PES.PesIdf, PES.PesSclNom
        , EMAPF.EmaPfDes
        , USRMA.PesIdf AS UsrMAID
        , EMAPF.EmaPfIdf
FROM [DB_CORP_CCB].[SchCRPCCB].[PES] AS PES WITH(NOLOCK)
INNER JOIN [DB_CORP_CCB].[SchCRPCCB].[DOCPF] AS DOCPF WITH(NOLOCK) ON DOCPF.PesIdf = PES.PesIdf
INNER JOIN [DB_CORP_CCB].[SchCRPCCB].[CTTPF] AS CTTPF WITH(NOLOCK) ON CTTPF.PesIdf = DOCPF.PesIdf
INNER JOIN [DB_CORP_CCB].[SchCRPCCB].[EMAPF] AS EMAPF WITH(NOLOCK) ON EMAPF.CttPfIdf = CTTPF.CttPfIdf
LEFT JOIN [DB_MA].[SchMA].[USRMA] AS USRMA WITH(NOLOCK) ON USRMA.PesIdf = CTTPF.PesIdf
WHERE DOCPF.DocTipPfCod = 1 AND CTTPF.CttTipCod = 2
    AND DOCPF.DocPfNum = 18677954856
	--AND DOCPF.DocPfNum = 32263773886
                            
    
SELECT 
	*
FROM [DB_CORP_CCB].[SchCRPCCB].[EMAPF] AS EMAPF WITH(NOLOCK)
WHERE EmaPfIdf = 43040
--dellamoce@policiamilitar.sp.gov.br