SELECT
*
FROM
	DB_EFETIVO.SchEfetivo.RHCB
WHERE LEFT(OPM_ATUAL,1) = 7 AND SLGCOD IN (1,2)
ORDER BY	
	CASE WHEN NIVEL IS NULL THEN 99 ELSE NIVEL END															
	,CASE WHEN POSCOD = 20 THEN ALMAN END
	,CASE WHEN POSCOD = 11 THEN DT_ULT_PROM END
	,CASE WHEN POSCOD = 4 THEN DT_ULT_PROM END																
	,CASE WHEN POSCOD = 23 THEN DT_ULT_PROM END																
	,CASE WHEN POSCOD = 25 THEN DT_ULT_PROM END																
	,CASE WHEN POSCOD != 16 THEN ALMAN ELSE 999999 END														
	,CASE WHEN LEFT(RHCB.RE,1) = 9 THEN 1 ELSE RHCB.RE END ASC															
	,CASE WHEN RHCB.RE IS NULL THEN 999999999																			
	 ELSE RHCB.RE END