-- CONSULTA DOS CÓDIGOS DE OPM DO MILITAR
SELECT 
	P.PesIdf, P.PesNom,
	E.OpmCod,
	U.UniAlcTipNom
FROM DB_CORP_CCB.SchCRPCCB.PES P
JOIN DB_CORP_CCB.SchCRPCCB.DOCPF D ON D.PesIdf = P.PesIdf
JOIN DB_RHCB.SchRH.EfeCbOpm E ON E.PesIdf = P.PesIdf
JOIN DB_RHCB.SchRH.UNIALCTIP U ON U.UniAlcTipCod = E.UniAlcTipCod 
WHERE D.DocPfNum = '15733225807' AND D.DocTipPfCod = 1

-- "ALTERAR" O CÓDIGO DA OPM DO MILITAR
SELECT * FROM [DB_RHCB].[SchRH].[EfeCbOpm]
WHERE PesIdf = 65333

-- NOME DA UOR PELO CÓDIGO
SELECT
	--*
	UorOpmNome, UorOpm 
FROM DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ
--WHERE uor = 67;
WHERE uor = 82
AND UorOpmAtvIdc = 1
;

-- DADOS DO MILITAR
SELECT 
	 POS_GRAD, CONCAT(RE, '-', DIG) AS RE, NOME_GUERRA,
	 OPM_NOME_ATUAL, UOR,
	 OPMCOD_EFETIVA, OPMCOD_ATUAL,
	 EMAIL_FUNCIONAL, EMAIL_PARTICULAR 
FROM DB_EFETIVO.SchEfetivo.Efetivo
WHERE CPF = '15733225807'

SELECT * FROM DB_EFETIVO.SchEfetivo.Efetivo
WHERE NOME LIKE '%STHEFANY ROITMAN%'

