--PRIMEIRO, DESCOBRE O PESIDF DA PESSOA
SELECT PesIdf, PesNom, PesSclNom, PesTipCod, PesNasDat, PesCpfMigNum, PesIclDat
FROM DB_CORP_CCB.SchCRPCCB.PES
WHERE PesCpfMigNum = '39305762875'
;

--DEPOIS, ADICIONÁ-LA NA TABELA ABAIXO, COM O AtvPrfCod = 2
SELECT AtvPrfCod, PesIdf, PesAtvPrfIclDat
FROM DB_CORP_CCB.SchCRPCCB.PESATVPRF
WHERE AtvPrfCod = 2;
