SELECT * FROM DB_CONAPLIC.SchCTRAPL.SFT
WHERE SftNom LIKE '%Administ%'
--WHERE SftCod = 118
;

--MENUS DO SOFTWARE
SELECT * FROM DB_CONAPLIC.SchCTRAPL.MNUSFT
WHERE SftCod = 127;

--FUNCIONALIDADES DO MENU
SELECT * FROM DB_CONAPLIC.SchCTRAPL.MNUSFTFND
WHERE MnuSftCod IN (225);

-- VERSÃO DO SOFTWARE
SELECT * FROM DB_CONAPLIC.SchCTRAPL.VRSSFT
WHERE SftCod = 127
;

--AMBIENTE CONTROLADO - VERSÃO SOFTWARE
SELECT * FROM DB_CONAPLIC.SchCTRAPL.ABECTRVRSSFT
WHERE VrsSftIdf IN(8130);

--BANCO DE DADOS
SELECT * FROM DB_CONAPLIC.SchCTRAPL.IDBSFTRLDSRVABECTR
WHERE VrsSftIdf IN(8130);

--AMBIENTE CONTROLADO E VERÃO DO SOFTWARE E SERVIDOR
SELECT * FROM DB_CONAPLIC.SchCTRAPL.SRVABECTRVRSSFT
WHERE VrsSftIdf IN(8130);

--LINGUAGEM DE PROGRAMAÇÃO
SELECT * FROM DB_CONAPLIC.SchCTRAPL.VRSSFTVRSLNGPGM
WHERE VrsSftIdf IN(8130);

--FRAMEWORK
SELECT * FROM DB_CONAPLIC.SchCTRAPL.VRSFMWVRSSFT
WHERE VrsSftIdf IN(8130);

