--> RETORNA O ID DO APARELHO PELO CPF DO USUÁRIO:
SELECT
U.CPF
,E.POS_GRAD
,E.RE
,E.NOME_GUERRA
,T.Token
FROM DB_APP_NOC.dbo.Usuario U
LEFT JOIN DB_APP_NOC.dbo.Token T ON U.ID_CPF = T.ID_CPF
LEFT JOIN (SELECT * FROM DB_EFETIVO.SchEfetivo.Efetivo WHERE UORCOD IN (50,51,52) AND UORCOD !='UORCOD NÃO CADASTRADA' AND RE! = 108435)  E ON U.CPF = E.CPF 
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ UOR ON UOR.Uor = E.UORCOD AND UOR.UorOpmAtvIdc = 1
WHERE 
UOR.UorOpmCod = 50 AND E.SLGCOD = 1


--CONSULTA SOMENTE DO DESENVOLVIMENTO
SELECT
U.CPF
,E.POS_GRAD
,E.RE
,E.NOME_GUERRA
,T.Token
FROM DB_APP_NOC.dbo.Usuario U
LEFT JOIN DB_APP_NOC.dbo.Token T ON U.ID_CPF = T.ID_CPF
LEFT JOIN (SELECT * FROM DB_EFETIVO.SchEfetivo.Efetivo WHERE UORCOD IN (50,51) AND UORCOD !='UORCOD NÃO CADASTRADA' AND RE!=108435)  E ON U.CPF = E.CPF 
LEFT JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ UOR ON UOR.Uor = E.UORCOD AND UOR.UorOpmAtvIdc = 1
WHERE 
--U.CPF = '35974496892'
UOR.UorOpmCod = 50 AND E.SLGCOD = 1 
ORDER BY E.EfetivoIdf





SELECT 
	*
FROM DB_APP_NOC.dbo.Usuario Usr
JOIN DB_APP_NOC.dbo.Token Tkn ON Usr.ID_CPF = Tkn.ID_CPF 
--WHERE Usr.CPF = '32263773886'
WHERE Usr.CPF = '17114643845'
;

--Token Amaro: ftPTgGCmIEMKlkUZ7DKtHz:APA91bGJ2UUE80bCRf1Gxs7doqjjVZoWhquq4yh8zm0YZfTC2lWJCKgCFJdorCdjMNiQINS1cCh9ED3CZOtDl7RzujtQCmpGwH7ZG-Bl5WGg95tUhZqBBBc
--Token Ten Edson: dUo-xYhkpkOGk5RmkiX5H-:APA91bEM_PlS_e0Lt8Ls94gDAEiQRVCoGnO5xt6O3U1nUuwZPswQ8aBmYEb6nZBMIcBZmchM9h0DYbmNb6HSqUdc7Qsu8Mtv7t765kH3yBP1Fqt_80xmkDM

SELECT ID_CPF, CPF, NotificationSound
FROM DB_APP_NOC.dbo.Usuario;

SELECT ID_CPF, Token
FROM DB_APP_NOC.dbo.Token
WHERE ID_CPF = 5;

UPDATE DB_APP_NOC.dbo.Token
SET Token=''
WHERE ID_CPF=0;

SELECT TipoRegistroCod, tipoRegistro, Sigla, TipoRegistroDescricao
FROM DB_APP_NOC.dbo.tipoRegistro;