SELECT * FROM DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ
WHERE UorOpmNome = '13.GB';

SELECT * FROM DB_EFETIVO.SchEfetivo.Efetivo
WHERE OPM_NOME_EFETIVA = '13.GB'
	AND SITUACAO = 'ATIVO'
	AND RE = 141499
;




SELECT 
	EFE.CPF , EFE.POS_GRAD , EFE.RE , EFE.DIG , EFE.NOME , EFE.NOME_GUERRA , EFE.OPM_NOME_EFETIVA 
	, EFE.OPM_NOME_ATUAL , EFE.BTL , EFE.CIA , EFE.UOR
FROM DB_EFETIVO.SchEfetivo.Efetivo EFE WITH(NOLOCK)
--JOIN DB_MUNICIPIO_OPM.SchUOR.VW_UOR_OPM_UOROPM_UORHRQ UOR WITH(NOLOCK) ON EFE.UORCOD = UOR.Uor 
WHERE EFE.BTL = '13.GB'
	AND EFE.SITUACAO = 'ATIVO'
	--AND EFE.RE = 141499
	--AND UOR.UorOpmAtvIdc = 1
	;