SELECT
	*
	--OCRNUM, OCRDAT, CADCOD, SITUACAOID, ENDERECO, ATENDIMENTOTIPOID, ID, STATUSID, DADOSCOMPLEMENTARES, COMANDANTECPF, MOTIVODEVOLUCAO, HOMOLOGADORCPF, DATAFINALIZACAO, DATAHOMOLOGACAO, ENDERECOINICIAL, POSSUIAGUIA, OCRGREDAT, OPMFATO, OPMATENDIMENTO, NATCOD, LOGRADOUROFINAL, NUMEROFINAL, COMPLEMENTOFINAL, BAIRROFINAL, MUNICIPIOIDFINAL, CEPFINAL, HISTORICO, LOGRADOUROINICIAL, NUMEROINICIAL, COMPLEMENTOINICIAL, BAIRROINICIAL, REFERENCIAINICIAL, MUNICIPIOIDINICIAL, SGB, GB, LOCALIZACAOFINAL, COMANDO, PB, LOCALIZACAOINICIAL, OcrChmDat, OcrRstCod
FROM DB_SDO.dbo.OCORRENCIA
WHERE OcrNum = 3269
AND CAST(OcrDat AS DATE) = '2025-04-11'
;

SELECT OcrDat, OcrNum, CadCod, HisOcrCod, HisOcrNum, HisOcrSeq, HisOcrDes, HisOcrPmReNum, HisOcrDat
FROM DB_SDO.SchOPR.HISOCR
WHERE OcrNum = 3269
AND CAST(OcrDat AS DATE) = '2025-04-11'
;


SELECT 
	--*
	OcrNum, OcrDat, CadCod, OcrChmDat, OcrGreDat, OcrNomSlt
	, LgrNom, OcrImvNum, OcrBaiNom, OcrNatIni
FROM DB_SDO.SchOPR.OCR
WHERE LgrNom LIKE '%Abraão de mor%'
AND OCRNUM = 3269
;