SELECT
	*
	--OCRNUM, OCRDAT, CADCOD, SITUACAOID, ENDERECO, ATENDIMENTOTIPOID, ID, STATUSID, DADOSCOMPLEMENTARES, COMANDANTECPF, MOTIVODEVOLUCAO, HOMOLOGADORCPF, DATAFINALIZACAO, DATAHOMOLOGACAO, ENDERECOINICIAL, POSSUIAGUIA, OCRGREDAT, OPMFATO, OPMATENDIMENTO, NATCOD, LOGRADOUROFINAL, NUMEROFINAL, COMPLEMENTOFINAL, BAIRROFINAL, MUNICIPIOIDFINAL, CEPFINAL, HISTORICO, LOGRADOUROINICIAL, NUMEROINICIAL, COMPLEMENTOINICIAL, BAIRROINICIAL, REFERENCIAINICIAL, MUNICIPIOIDINICIAL, SGB, GB, LOCALIZACAOFINAL, COMANDO, PB, LOCALIZACAOINICIAL, OcrChmDat, OcrRstCod
FROM DB_SDO.dbo.OCORRENCIA
WHERE 
	OcrNum = 2480 AND 
	CAST(OcrDat AS DATE) = '2025-08-11'
	AND GB = '13.GB'
;

SELECT OcrDat, OcrNum, CadCod, HisOcrCod, HisOcrNum, HisOcrSeq, HisOcrDes, HisOcrPmReNum, HisOcrDat
FROM DB_SDO.SchOPR.HISOCR
WHERE OcrNum = 2480
AND CAST(OcrDat AS DATE) = '2025-08-11'
;


SELECT 
	--*
	OcrNum, OcrDat, CadCod, OcrChmDat, OcrGreDat, OcrNomSlt
	, LgrNom, OcrImvNum, OcrBaiNom, OcrNatIni
FROM DB_SDO.SchOPR.OCR
WHERE LgrNom LIKE '%Abraão de mor%'
--AND OCRNUM = 3269
;











--TRAZ TODAS AS OCORRÊNCIAS POR PERÍODO QUE USARAM DEA:
SELECT
	--*
	Ocr.OCRNUM AS Talao, CONVERT(VARCHAR(10), Ocr.OcrDat, 103) AS Data_Ocr, Vtr.PTRIDF AS Viatura, Ocr.LOGRADOUROFINAL AS Endereco, Ocr.NUMEROFINAL AS Ende_Numero, Ocr.BAIRROFINAL AS Bairro,
	--RIGHT(REPLICATE('0', 11) + CAST(Ocr.COMANDANTECPF AS VARCHAR(11)), 11) AS cpf_formatado,
	Efe.POS_GRAD AS PosGrad, Efe.RE, efe.DIG AS Dig_RE, efe.NOME_GUERRA AS Nome_Guerra
FROM DB_SDO.dbo.OCORRENCIA Ocr WITH(NOLOCK)
JOIN DB_SDO.dbo.VITIMA Vit WITH(NOLOCK) ON Ocr.ID = Vit.OCORRENCIAID 
JOIN DB_SDO.dbo.VIATURAOCORRENCIA Vtr WITH(NOLOCK) ON Ocr.ID = Vtr.OCORRENCIAID 
JOIN DB_EFETIVO.SchEfetivo.Efetivo Efe WITH(NOLOCK) ON RIGHT(REPLICATE('0', 11) + CAST(Ocr.COMANDANTECPF AS VARCHAR(11)), 11) = Efe.CPF
WHERE 
	CAST(Ocr.OcrDat AS DATE) >= '2025-01-01'
	AND Ocr.GB = '13.GB' AND Ocr.SGB = '1.SGB '
	AND Vit.USODEA = 1
ORDER BY Ocr.OcrDat
;





