SELECT 
	DATA_OCR, DATA_GERACAO, TALAO, CAD, CABINE, GB, ENDERECO, NUMERAL, BAIRRO
	, REFERENCIA, MUNICIPIO, TEL_SOLIC, NATUREZA, SITUACAO, LONG, LAT, US_PFX
	, HISTORICO, ESTACAO, PRIORIDADE
FROM DB_CARGA_SIOPM.SchNOC.VW_OCR WITH(NOLOCK)
--ORDER BY SITUACAO DESC, DATA_GERACAO DESC; 

--> OCORRÊNCIAS DO CBM
SELECT * FROM DB_CARGA_SIOPM.SchNOC.VW_OCR WITH(NOLOCK)
--WHERE GB IN ('01.GB','02.GB','03.GB','04.GB','05.GB','08.GB','17.GB','18.GB')--('05.GB')
WHERE GB IN ('13.GB')
	--AND SITUACAO = 'PENDENTE'
	--AND SITUACAO = 'ATENDIMENTO'
	--and TALAO = 7861 
	--and ENDERECO like '%Souza%' 
ORDER BY SITUACAO DESC, DATA_GERACAO DESC
;



--> OCORRÊNCIAS APENAS DE RESGATE DE EB's ESPECÍFICAS
SELECT 
	DATA_GERACAO, TALAO, ESTACAO, SITUACAO, 
	--US_PFX,
	LEFT(US_PFX, CHARINDEX('-', US_PFX) - 1) AS PREFIXO,
	NATUREZA, ENDERECO, 
	NUMERAL, BAIRRO, MUNICIPIO, REFERENCIA, HISTORICO
FROM DB_CARGA_SIOPM.SchNOC.VW_OCR WITH(NOLOCK)
WHERE GB IN ('13.GB')
	AND (US_PFX LIKE 'UR%' OR US_PFX LIKE 'USA%' OR US_PFX IS NULL)
	AND 
		(
			ESTACAO = 'EB - Boa Vista'
			OR
			ESTACAO = 'EB - Aeroporto'
			OR
			ESTACAO = 'EB - Jardim Alegre'
			OR
			ESTACAO = 'EB - Mirassol'
			OR
			ESTACAO = 'EB - Vila União'			
		)
ORDER BY SITUACAO DESC, DATA_GERACAO DESC
;


SELECT * FROM DB_CARGA_SIOPM.SchNOC.VW_OCR;


SELECT CHECKSUM_AGG(BINARY_CHECKSUM(*)) FROM DB_CARGA_SIOPM.SchNOC.VW_OCR




SELECT
	--COUNT(*)
	* 
	--OcrDat, OcrNum, CadCod, AleCabNum, AleSitCod, AlePriOri, AlePriAtu, AleRtoFlg, AleLigRtoQtd, AlePpgFlg, AleEndOcr, AleNatIniCod, AleSstCod, AleGreDat, AleSrvCod, AleOpmDes, AleOpmCod, AlePriCod, AleUtmx, AleUtmy, AleCabAtdInd, AleCplNatCod, AleDtlCplNatDes, AleNatDes, AleDtlCplNatCod, AleCplNatDes, AleCriInd, AleAgdDat, AleAgdInd, AleRagInd, AleFimTsoInd, ALEIDFAGPGEOSST, AleOcrDphInd, AleOcrGeog, AleLat, AleLon, AlePoiCod
FROM DB_CARGA_SIOPM.SchTMP.ALE
WHERE LEFT(AleOpmCod, 3) = 701 --701: UNIDADES DO CBM
	AND OcrNum = 8561 
	--AND AleSitCod = 'P' -- PENDENTES
	--AND AleSitCod = 'A' -- EM ATENDIMENTO
	--AND AleSitCod = 'X' -- PARA ENCERRAMENTO 
;
--AlePriCod
	--PRIORIDADE 2: URGENTE
	--PRIORIDADE 1: NORMAL

