--> OCORRÊNCIAS - SUPERVISÃO DELEGADA
SELECT * FROM DB_CARGA_SIOPM.SchNOC.VW_OCR
--WHERE GB IN ('01.GB','02.GB','03.GB','04.GB','05.GB','08.GB','17.GB','18.GB')--('05.GB')
WHERE GB IN ('13.GB')
ORDER BY SITUACAO DESC, DATA_GERACAO DESC
;




SELECT 
	DATA_GERACAO, TALAO, GB, ESTACAO, MUNICIPIO, NATUREZA, SITUACAO
FROM DB_CARGA_SIOPM.SchNOC.VW_OCR
--WHERE GB IN ('01.GB','02.GB','03.GB','04.GB','05.GB','08.GB','17.GB','18.GB')--('05.GB')
WHERE GB IN ('13.GB')
ORDER BY SITUACAO DESC, DATA_GERACAO DESC
;